### ISSUE TITLE
For wram0 pointer wcxyz, BANK(wcxyz) does not evaluate to 0 let alone a char

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#117]
Given the following code:

    SECTION "Test WRAM", WRAM0
    wc000::

    SECTION "Test ROM", HOME
    RST_00::
        ld a, BANK(wc000)
        ret

Expected result:
0000: 3e 00 c9 ...

Error message: Value must be 8-bit

**Comment by PikalaxALT** [comment]
#121

**Comment by Ben10do** [comment]
The PR's been merged - this issue can be closed.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/pull/121
