### ISSUE TITLE
Byte alignment for data, to enable usage of DMA

### ISSUE THREAD

**Issue by Ben10do** [rednex/rgbds#124]
Both OAM DMA and VRAM DMA require that their source data is aligned in intervals of $100 or $10 bytes respectively, such that their starting addresses end with `$XX00` or `$XXX0` respectively.

At present, `rgbds` does not provide support for such alignment of data in any section, requiring that a fixed position is specified instead. It'd be really helpful if `rgbasm` would allow such alignment to be specified, and if `rgblink` could enforce the alignment when assigning sections.

Any syntax suggestions for this would be greatly appreciated.

**Comment by Ben10do** [comment]
I had two ideas for how the syntax in the assembler could work:
1) Specify the alignment where the exact location would normally be specified, using either `$XXX0` or `$XX00`:
    - `SECTION "VRAM DMA Example", ROMX[$XXX0]`
    - `SECTION "OAM DMA Example", WRAM0[$XX00]`

2) Add an extra attribute called `ALIGN`, that works in a similar fashion to `BANK`. The parameters are either `$10` or `$100`, although this could theoretically handle any desired alignment:
    - `SECTION "VRAM DMA Example", ROMX, ALIGN[$10]`
    - `SECTION "OAM DMA Example", WRAM0, ALIGN[$100]`

I personally like the first one better (since I think the intention is clearer), but it's not syntax that's seen elsewhere in `rgbasm`. Thoughts?

**Comment by AntonioND** [comment]
I don't like 1 or 2. There are more reasons to align data than just DMA, and I see no reason why limiting this to 16 or 256 bytes is a good idea, I suggest something like the GNU assembler, something like `ALIGN[2]`, where the 2 means the number of bits to set to 0 in the address. The problem I see is that I may want to have 2 or more labels aligned to different boundaries in the same section, and this system wouldn't allow that.

**Comment by Ben10do** [comment]
That's fair. I did like 1 for the DMA examples, but it would be silly to use something like that over a more general solution. I'm not too fussed if we use the number of bits or a multiple of bytes.

I'm not as worried about data alignment within a section, since at least you have control over the data there, and the size of that data. However, I do see the appeal of also including something that would also allow padding within a section (as I believe `gas` does); perhaps some kind of built-in macro/function could accomplish this?

**Comment by AntonioND** [comment]
As far as I see, the only way to do this is by telling the linker how to align sections. An align keyword would break things like the `jr` distance checks because the padding would have to be inserted by the linker and the checks are done by the assembler.
