### ISSUE TITLE
gnu/linux binary (i386 or amd64) of rgbfix

### ISSUE THREAD

**Issue by nitrofurano** [rednex/rgbds#126]
where can we find gnu/linux binary of rgbfix? i’m struggling a lot trying to compile it...
and can we find rgbfix, or whole rgbds, in some ppa?
thanks in advance! :)

**Comment by AntonioND** [comment]
As far as I know, it's nowhere. What's the problem, anyway?

**Comment by AntonioND** [comment]
I'm going to close this because distributing Linux binaries isn't as easy as on Windows.

If you really need to compile `rgbfix` on its own, `make rgbfix` should simplify things, as you won't need to care about yacc, flex, pkg-config or libpng.
