### ISSUE TITLE
New format for documentation

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#129]
The documentation should be migrated to markdown or reStructuredText, it's easier to edit and we could use the same format for all of it, including the README.

I think that we should use reStructuredText, it has more flexibility than markdown in my opinion, but I'm open to discussion here.

**Comment by rogersachan** [comment]
@AntonioND www.readthedocs.org is the only free solution for hosting the new rst docs, but is a very neat and easy to use project.

**Comment by AntonioND** [comment]
I wasn't even talking about hosting it, my concern is the generation of it. It's really painful to modify the html docs and really easy to modify markdown languages as part as regular commits, that's why I propose the change.

The hosting is a secondary issue.

We could even provide a Makefile target for anyone to generate html documentation from it.

**Comment by Ben10do** [comment]
Seeing as a new repo has recently been made for the express purpose of hosting the documentation, we may as well make use of it, regardless of if we generate it ourselves or use GitHub Pages or something.

**Comment by AntonioND** [comment]
http://zverovich.net/2016/06/16/rst-vs-markdown.html

**Comment by rogersachan** [comment]
@AntonioND I think the rtd approach is better because then the docs will be automatically built **with artifacts included** (which we cannot do in Travis CI)

**Comment by Ben10do** [comment]
Regardless of which approach we go with for the future, should I append the existing documentation to show that `ALIGN` and `OAM` exist and how to use them?

*(I guess it depends on how long you think it's going to take to migrate them…)*

**Comment by AntonioND** [comment]
Oh, yeah, they should probably be documented in the current format. It's easier to adapt it to the new format than to remember to document it.

**Comment by naavis** [comment]
Great to see something happening on the documentation front! Old documentation was my biggest gripe when I started using RGBDS.

**Comment by AntonioND** [comment]
I'm not sure right now about using a new format. I can see that using something more advanced than man pages could be nice, but I also think that man pages are useful and maintaining two different sets of documentation is a pain.
