### ISSUE TITLE
Remove support for old object files

### ISSUE THREAD

**Issue by Ben10do** [rednex/rgbds#132]
(Continuing the discussion from #125)

@AntonioND:
"…I'm wondering whether we actually need to maintain compatibility with the old obj formats. Any opinions? It would make the code more maintainable, and I see no advantage to keeping the old format (unless you have object files of a really really old rgbds and for some strange reason you want to use them)."

@Ben10do:
"…I've no problem with keeping compatibility with RGB1-3, since their differences are subtle enough that it's quite easy to keep the compatibility there.

"RGB0, on the other hand, requires quite a lot of extra (often duplicated) code. Seeing as RGB0 has co-existed with RGB1 for as long as this project's been under Git, I think users will have had ample time to reassemble (😂). As a result, I see little point in keeping it supported."

@AntonioND:
"But that's exactly my point, anyone using this repository nowadays can just reassemble, we don't need to maintain compatibility with every single small variation."

@Ben10do:
"True. So, I'd say that we definitely axe RGB0, but I don't mind if we axe RGB1-2.

"To do this, should I amend this PR, or make a new one after this has been merged? (And should I definitely axe RGB1-2?)"

@AntonioND:
"Let's keep this PR as it is now and decide later."

**Comment by AntonioND** [comment]
Let's leave this here for a while in case someone wants to say something.
