### ISSUE TITLE
[Feature request] Allow include in linkerscripts

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#147]
Makes very large linkerscripts a lot more manageable. Not sure of how feasible this would be.

**Comment by AntonioND** [comment]
Something that just copies the contents of a file inside another one?

**Comment by aaaaaa123456789** [comment]
Pretty much, kinda like C's #include, or the include mechanism in rgbasm.

**Comment by AntonioND** [comment]
Yeah, that can be done. We could ago have support for multiple linkerscripts that you can pass using the command line.
