### ISSUE TITLE
Linkerscripts ignore ROMX placements

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#148]
For some reason, the linker is ignoring anything I write about ROMX placements. All other sections work just fine, but the ROMX ones are failing. For instance, take this section:

```
ROMX $05
	org $4000 ;dummy, avoid potential linker relocations
	align 8
	"Demo Sine"
	"Code 5"
	"Map block data 1"
	"Map Scripts small 1"
	"Sprites 2"
	"Tileset Data small 1"
```

The actual locations of these sections end up being 04:4000, 04:4100, 04:6fcf, 05:72e9, 1d:7608 and 25:7c34. Something went wrong, clearly.

**Comment by AntonioND** [comment]
Yeah, I'm surprised it even worked in the first place. Fixed here: https://github.com/rednex/rgbds/commit/adef2e18cc8b269723109e1a316246e6a2e21513

**Comment by aaaaaa123456789** [comment]
Seems to be fixed.
