### ISSUE TITLE
Linker is miscalculating addresses

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#149]
Long example incoming:

https://gist.github.com/aaaaaa123456789/2eefb1e60cffb9fee0b0b64597707bec

As you can see there, the linker is suddenly resolving the `wPlayerDataEnd - wPlayerData` expression incorrectly for no apparent reason, resulting in an area that is $83 bytes long as opposed to $82a. Nothing in wram.asm or sram.asm was changed; I only updated rgbds to the current version.

**Comment by AntonioND** [comment]
It's not that the linker is miscalculating the address, it's miscalculating the size.

The thing is that the size of a section comes in the object file generated by `rgbasm`, so it's not a problem of the linker but of the assembler. The linker simply can't do this.

This sounds really weird to me, `rgblink` isn't prepared for sections with size undetermined at link time, it's only prepared to do simple calculations with labels (check `include/link/mylink.h`) and replace a 1 or 2-byte placeholder left by the assembler.

Can you check the map file generated before the compilation broke?

**Comment by aaaaaa123456789** [comment]
I don't have the previous map file, but I know (from having seen and used
it before) that the sizes were what they should be. That was when I was
still using the old rgbds with fixed section order — I updated directly
from that to the current one.

Do you need any additional information?

**Comment by AntonioND** [comment]
But that couldn't be working. As I've said, `rgblink` cannot modify the size of a section when linking, the size must be known when assembling. I've taken a look at how the `DS` keyword works, and there's no way that could have worked before (function `out_Skip()`).

Could you checkout an old version of this repo, compile your code with that version, and check the map file? Or create a simple project with 2 object files that works correctly in an old version and doesn't work now.

**Comment by aaaaaa123456789** [comment]
I'll do that when I get back home — or we could give you access to the
repository, if you prefer.

**Comment by AntonioND** [comment]
As you wish... But everywhere I look it says that the size is already defined when the object file is generated: https://github.com/rednex/rgbds/blob/master/include/asm/mylink.h#L31

**Comment by aaaaaa123456789** [comment]
Finally got in touch with the guy who handles this stuff; you should have
an invite to the repo and read access. Go ahead and check, please.

**Comment by AntonioND** [comment]
Ok, so you are including one file into the other one effectively creating a single object file. That explains that `rgbasm` can resolve the size of the section. If I try to place the sections in different object files `rgbasm` says that the symbols are undefined.

In short:

`wram.asm`
```
SECTION "w", WRAM0
wStart::
DS 20
wEnd::
```

`sram.asm`
```
IMPORT wStart
IMPORT wEnd
SECTION "s", SRAM, BANK[0]
sStart:
DS wEnd - wStart
sEnd:
```

`build.sh`
```
rgbasm -o wram.o wram.asm                                                
rgbasm -o sram.o sram.asm
rgblink -o test.gb -m test.map -n test.sym wram.o sram.o
```

This fails as expected in the second line. However, this works and creates the two sections correctly:

`both.asm`
```
SECTION "w", WRAM0
wStart::
DS 20
wEnd::

SECTION "s", SRAM, BANK[0]
sStart:
DS wEnd - wStart
sEnd:
```

`build.sh`
```
rgbasm -o both.o both.asm
rgblink -o both.gb -m both.map -n both.sym both.o
```

I'll keep looking at this.

**Comment by AntonioND** [comment]
W. T. F.

You are subtracting labels in different sections! That's why rgbasm is going crazy, it calculates the address relative of each label inside its section, then it subtracts them. If they are in different sections, the address relative to each start of section is used. It has taken me forever to realize that because your list of labels is insanely long.

You can't do this. The fact that rgbasm doesn't complain about it doesn't mean it's right. The address of each label is undetermined when assembling, which means that only relative addresses can be calculated.

It worked before adding the linkerscript because rgbasm actually knew the address of each label as you were assigning the base address of the section in the source code, so it could use the absolute address instead of the relative one.

Sorry, you'll have to fix your code so that all labels you use for calculations are in the same section.

**Comment by AntonioND** [comment]
This one was pretty hard to find...

**Comment by AntonioND** [comment]
You can just calculate partial sizes of each section and add them together.

**Comment by aaaaaa123456789** [comment]
Maybe this should raise a warning, if not a straight error. Will fix.

**Comment by AntonioND** [comment]
That should be an error, I completely agree, but that's easier said than done. I can think of a really hacky way to detect this kind of problem, but I'm not sure it's even doable without breaking stuff on the way. A proper solution is complicated. I'll see what I can do, anyway.

**Comment by AntonioND** [comment]
Actually, it may be easier than I originally thought. Tomorrow I'll take a look at it.
