### ISSUE TITLE
OPT_CONTWRAM was not meant to restrict VRAM banking

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#166]
The only reason why I added OPT_CONTWRAM was to allow for a continuous 2000h-byte WRAM section.  A recent commit reappropriates this flag, renamed OPT_DMG_MODE, to also disable VRAM banking.  However, there are several titles that have DMG wram behavior but take advantage of CGB functions such as 1:9800-9fff (bg attributes).

Furthermore, this version breaks [Robopon](https://github.com/pikalaxalt/robopon).

**Comment by AntonioND** [comment]
You can't seriously expect me to know ever single way this is being used. This change just made sense, but don't worry, I'll revert this. Things in development break, but I think I've been pretty reasonable untill now, taking care of the needs of you disassemblers (yes, I don't break your code on purpose) and fixing some old issues, and even finding bugs in poorly organised code that I didn't write (powered anyone?).

I'll just create a new flag that enables the continuous WRAM flag and prohibits VRAM bank 1.

**Comment by AntonioND** [comment]
https://github.com/rednex/rgbds/commit/5679c7066b0f7365f0696fd07f539e5b9dd82a7d
