### ISSUE TITLE
Error with inclusions in linkerscripts

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#172]
My current linkerscript is nothing but `INCLUDE` statements (and a short VRAM section at the end) — I basically split the old linkerscript into four pieces (ROM0, ROMX, WRAM, SRAM) and put each piece in a separate file, which I now include. So I know that each of the "pieces" is syntactically correct, since they all worked until yesterday.
However, when I try to compile the ROM, I get this error:
```
error: contents/homebank.link(0) -> contents/contents.link(1):
	Linkerscript parse error: "syntax error"

make: *** [pokeprism.gbc] Error 1
```

The main contents.link file is just this:
```
INCLUDE "contents/homebank.link"
INCLUDE "contents/romx.link"
INCLUDE "contents/wram.link"
INCLUDE "contents/sram.link"

VRAM 0
	org $8000 ;avoid linker relocations
	"VRAM0"
VRAM 1
	org $8000 ;avoid linker relocations
	"VRAM1"
```

...and the homebank.link file simply contains ROM0 sections in the usual way.

Is linkerscript inclusion working properly?

**Comment by AntonioND** [comment]
Well, it seems that this happens only if the first like of a linkerscript isn't empty. A comment counts as empty. For now, you can leave an empty line there, I'll try to get it fixed by Sunday at most.

**Comment by AntonioND** [comment]
Should be fixed here: https://github.com/rednex/rgbds/commit/f7f697c2677be5fe456effeb6f27138f62c1bc42
