### ISSUE TITLE
rgbgfx in v0.2.5

### ISSUE THREAD

**Issue by yenatch** [rednex/rgbds#180]
In Cygwin, running rgbgfx.exe from the v0.2.5 release results in:
```
./rgbgfx.exe: error while loading shared libraries:
libpng16-16.dll: cannot open shared object file: No such file or directory
```

libpng16-16.dll (and zlib1.dll) are present in the 0.3.0 and 0.3.1 releases.
Can the dlls be included in the 0.2.5 release?

**Comment by AntonioND** [comment]
Let's see how it goes now, I've compiled for 32 and 64 bit. I've just copied the targets of the current Makefile in the one at tag v0.2.5, in case someone wonders how I've done it.

**Comment by AntonioND** [comment]
@yenatch, have you had time to test the new binaries?

**Comment by AntonioND** [comment]
This seems to be solved, so I'll close it. If there are problems, reopen it.
