### ISSUE TITLE
Source distribution rgbds-0.3.2.tar.gz contains object files

### ISSUE THREAD

**Issue by Sanqui** [rednex/rgbds#186]
![image](https://user-images.githubusercontent.com/289437/28026014-23f866a8-6595-11e7-80db-cae90bf6d51c.png)

This leads to cryptic errors on different platforms:

```
cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -o rgbasm src/asm/asmy.o src/asm/charmap.o src/asm/fstack.o src/asm/globlex.o src/asm/lexer.o src/asm/main.o src/asm/math.o src/asm/output.o src/asm/rpn.o src/asm/symbol.o src/asm/locallex.o src/extern/err.o src/extern/reallocarray.o src/extern/strlcpy.o src/extern/strlcat.o -lm
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: src/asm/asmy.o: Relocations in generic ELF (EM: 62)
src/asm/asmy.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [Makefile:80: rgbasm] Error 1
```

`make clean` should fix this, but those files should not be present in the source in the first place.

**Comment by AntonioND** [comment]
Oh, sorry, that's obviously a mistake. I must have forgotten to clean the folders before compressing them because I was more concerned about the binaries for Windows... I'll fix it in a few hours as soon as I get home.

**Comment by Sanqui** [comment]
I think it might not even be necessary to include these packages in releases, since GitHub provides 
"Source code (tar.gz)" which should be the same.

**Comment by AntonioND** [comment]
Well, this is fixed. It's true that it isn't strictly necessary to include this compressed file, I do it mainly to be consistent with the previous releases. Also, it doesn't take too long to do if you compare it to what it takes me to boot the VM and build them for Windows.

**Comment by Sanqui** [comment]
Got it, thanks!

**Comment by bentley** [comment]
Here are some reasons why I create my own tarballs for GitHub releases:

* Packagers like stable checksums. There’s no guarantee that GitHub won’t, e.g., change their gzip settings, thus breaking anything that relies on the URL referring to the exact same file.
* GitHub tarballs don’t include submodules. (Not relevant for RGBDS.)
* It’s conventional for release tarballs to include generated configure scripts so end users don’t have to run autoconf. (Again, not relevant for RGBDS.)
