### ISSUE TITLE
Disallowing negative constants in `ds` breaks backwards compatibility

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#190]
It has been a very common usage to use a negative `ds` to declare multiple labels on the same WRAM area, such as:

```
wLabelA1:: ds 2
wLabelA2:: ds 4

  ds wLabelA1 - @

wLabelB1:: ds 3
wLabelB2:: ds 3
```

That code would be used to declare a 6-byte area. While it _is_ technically possible to interleave the labels, doing it this way is much clearer when hundreds of such cases are involved.

Commit fe65e07 breaks this, making rgbds backwards-incompatible and removing something that was a feature, not a bug. (Perhaps add a flag to treat it as a bug if needed, but it shouldn't be the only behavior.)

**Comment by AntonioND** [comment]
That was a bug, defining a negative size simply doesn't make sense. And it's even clearer that it was a bug when you consider that it didn't even check if the bank number was negative, or the address in the bank, or things like that.

Allowing `DS` to accept negative numbers is a terrible idea because it has a few side-effects and allowing negative values would just break things: https://github.com/rednex/rgbds/blob/master/src/asm/output.c#L679 It doesn't even make sense, in ROM sections it would just treat the value as positive and write a huge amount of bytes (or maybe, with a bit of luck, it would detect that it doesn't fit and stop).

I'm going to leave this open for a while to see what other people think but, honestly, that's a bug in your code. As far as I know, the commands meant to do that are `RSSET`, `RERESET`, `RB` and `RW`.

**Comment by aaaaaa123456789** [comment]
If you consider it a true bug, what's your suggester alternative?

**Comment by Ben10do** [comment]
Am I right in saying that you'd effectively like something along the lines of a C union?

**Comment by aaaaaa123456789** [comment]
Correct, including the part where members needn't be the same size.

**Comment by PikalaxALT** [comment]
To be fair, the entirety of the use of `ds (negarg)` has been in RAM sections where it does make sense given the lack of a sane alternative.

**Comment by NieDzejkob** [comment]
I don't see how RS commands can be used to implement this:
```
; used in engine state A
one: dw
two: ds 8
three: ds 4
    ds @ - one
; used in engine state B
eins: ds 3
zwei: db
drei: ds 4
foo: db
bar: ds 5
```

**Comment by drifloony** [comment]
Solution: abandon the recent versions of rgbds and fork the old, sane version

**Comment by AntonioND** [comment]
Why is the old version sane?

**Comment by aaaaaa123456789** [comment]
This is starting to feel like a repeat of #136. May I suggest you guys check if you aren't actually removing implemented behavior when implementing a fix? The issue is the same — codebases were misusing feature X to achieve a certain behavior, and with feature X updated/fixed there is no way of achieving the intended behavior, using feature X or any other.

**Comment by AntonioND** [comment]
It is a repeat. What I don't want to do is to allow inconsistent behaviours with this. Allowing negative values in ROM sections doesn't make any sense, so it has to be prohibited there. And in RAM sections it can be a real problem if you do it right at the beginning:
```
SECTION "Test", WRAM0[$C100]
StackTop:: DS -$100
```
The linker would treat that section as something that increases the free space in WRAM0. How is that sane?

However I remember someone asking for overlappable sections.

The thing is: How exactly are you using this?

**Comment by aaaaaa123456789** [comment]
This is a small excerpt from the Prism code:

```
wc6d0::
PlayerSDefLevel:: ; c6d0
	ds 1
PlayerAccLevel:: ; c6d1
	ds 1
PlayerEvaLevel:: ; c6d2
	ds 1
PlayerAbility:: ; c6d3
	ds 1
PlayerStatLevelsEnd::

; ... $60 bytes' worth of WRAM label declarations removed ...

BattleEnded:: ; c734
	ds 1

wWildMonMoves:: ds NUM_MOVES ; c735
wWildMonPP:: ds NUM_MOVES ; c739
wAmuletCoin:: ds 1 ; c73a
wSomeoneIsRampaging:: ds 1 ; c73b
wPlayerJustGotFrozen:: ds 1 ; c73c
wEnemyJustGotFrozen:: ds 1 ; c73d

wPlayerJustSentMonOut:: ds 1
wEnemyJustSentMonOut:: ds 1
wBattleEnd::
; Battle RAM

; c741
	ds wc6d0 - @
wTrademons::
wPlayerTrademon:: trademon wPlayerTrademon
wOTTrademon::     trademon wOTTrademon
wTrademonsEnd::
wTradeAnimPointer::
	ds 2
wLinkPlayer1Name:: ds NAME_LENGTH
wLinkPlayer2Name:: ds NAME_LENGTH
wLinkTradeSendmonSpecies:: ds 1
wLinkTradeGetmonSpecies:: ds 1
	ds wc6d0 - @

; naming screen
wNamingScreenDestinationPointer:: ds 2 ; c6d0
wNamingScreenCurrNameLength:: ds 1 ; c6d2
wNamingScreenMaxNameLength:: ds 1 ; c6d3
wNamingScreenType:: ds 1 ; c6d4
wNamingScreenCursorObjectPointer:: ds 2 ; c6d5
wNamingScreenLastCharacter:: ds 1 ; c6d7
wNamingScreenStringEntryCoord:: ds 2 ; c6d8
	ds wc6d0 - @

; town map
wTownMapCursorObjectPointer:: ds 2 ; c6d5
wTownMapCursorLandmark:: ds 1 ; c6d7
wTownMapPlayerIconLandmark:: ds 1 ; c6d8
wTownMapCursorX:: ds 1
wTownMapCursorY:: ds 1
wTownMapRegion:: ds 1
	ds wc6d0 - @
```

The player can only be in one of those situations (in a battle, checking the town map, naming something) at a time, so the usage of those WRAM subsections is disjoint; therefore, they are put in the same WRAM location to save some space. They all have the same base address and extend for as long as needed; if the blocks have different lengths, the longest such block is declared last (so as to reserve the right amount of WRAM) unless it happens at the end of a section.

Also, while I've seen stack declarations just like the one you quote above in other repositories , I tend to fix them to the "proper" form:

```
SECTION "Stack", WRAM0[$c000]
  ds $100
StackTop::
```

**Comment by aaaaaa123456789** [comment]
I'll also point out that forcing those overlapping blocks to go in different sections causes issues due to what happened in #149.

**Comment by AntonioND** [comment]
Ok, fair enough. What about this?
```
SECTION "Test", WRAM0
Label: DS 1000
DS -1000
Label2: DS 1
```
The size of that section is 1.

**Comment by aaaaaa123456789** [comment]
We've never run into issues with that because we use fixed sections in WRAM, but I agree that it is a problem.

I'm trying to come up with a complete example of what could be a solution, but I can't see this happening without new keywords.

**Comment by aaaaaa123456789** [comment]
Something like this should work:

```
SECTION "test", WRAM0[$c000]
wA1:: ds 2
wA2:: ds 2

  union
wB1:: ds 3
wB2:: ds 1
wB3:: ds 2
  unext
wC1:: ds 4
wC2:: ds 4
  unext
wD1:: ds 2
wD2:: ds 1
  uend

wE1:: ds 2
wE2:: ds 2
```

This should result in something like this:
```
C000 wA1
C002 wA2
C004 wB1
C007 wB2
C008 wB3
C004 wC1
C008 wC2
C004 wD1
C006 wD2
C00C wE1
C00E wE2
```

This is an example; I'll leave the exact syntax up to you. But this is pretty much what we're attempting to achieve via negative `ds` declarations.

**Comment by AntonioND** [comment]
Actually, I like that idea. I'm just not sure if they should be stackable or not, but the general idea is clean and says clearly what it's trying to do.

**Comment by aaaaaa123456789** [comment]
I don't believe we're stacking them currently, but I see no harm in that.

**Comment by PikalaxALT** [comment]
Maybe do `endu` instead of `uend` to retain naming consistency in rgbds keywords.

**Comment by Ben10do** [comment]
This kind of syntax was what I had in mind as soon as I suggested unions - sorry for not bringing it up sooner!

I'll try and look into implementing this. In the meantime, should we retcon `ds` to allow negative values (but deprecate this ability), in order to ease the transition? Of course, this is something that will disappear eventually, but I'm wondering if that should be now or later.

Just a thought - seeing as we're occasionally eliminating bugs that are being relied on, it could be worth doing [something like this](https://swift.org/source-compatibility/) to better evaluate when source-breaking changes occur. This would also allow us to alert developers of these projects if source-breaking changes *are* absolutely necessary.

**Comment by Ben10do** [comment]
OK, here's one thing off the list in my last comment: #193. Take a look, and let me know if it's a good replacement or not.

**Comment by Ben10do** [comment]
OK, I'm glad that's sorted.

Now, should we also reenable (but deprecate) `ds` with negative values, in order to ease the transition?

I'm not expecting that we keep that support forever; either one or a few versions should be OK. This would also help users become aware of the existence of unions.

**Comment by aaaaaa123456789** [comment]
It would certainly avoid a repeat of the "all at once" transition that was
linkerscripts.

**Comment by AntonioND** [comment]
Just out of curiosity, which projects have this problem? As far as I know:

- Pokemon Crystal and Red: But they are using an outdated version anyway, this change doesn't make things worse. They might as well fix it when/if they update the version.
- Prism: Under active development, so the devs can fix it. And the devs can use an old version of rgbds until they fix it, which shouldn't take too long to do.

**Comment by PikalaxALT** [comment]
pikalaxalt/robopon and pikalaxalt/telefang_gb make use of `ds wCurUnionOrigin - @`

**Comment by aaaaaa123456789** [comment]
I think pokepinball uses it as well, and I moved that one to 0.3.1 not too
long ago.
