### ISSUE TITLE
yacc: 2 shift/reduce conflicts, 3 reduce/reduce conflicts.

### ISSUE THREAD

**Issue by wiseguy12851** [rednex/rgbds#192]
Ubuntu 17.05 Fresh installation and rgbds 0.3.2, followed all build instructions and got this error message

yacc: 2 shift/reduce conflicts, 3 reduce/reduce conflicts.

upon running make.

Don't know where to go from here.

**Comment by AntonioND** [comment]
This is a known issue: https://github.com/rednex/rgbds/issues/44

It shouldn't prevent you from being able to compile it and it shouldn't cause any runtime errors.

**Comment by wiseguy12851** [comment]
I ran make and got this message as the only output. Does that mean it compiled since you said it shouldn't prevent me from compiling or does it mean I need to run a different command.

I guess I'm used to my console being flooded with compile progress and activity on make but in less than a second it flashed this message and was done.

**Comment by AntonioND** [comment]
If there isn't any error message from make, everything should be fine. Just check that the binaries are there.

**Comment by wiseguy12851** [comment]
Yes binaries there, thanks, went on ahead and installed them.
