### ISSUE TITLE
Expand continuous integration to test with various GB projects

### ISSUE THREAD

**Issue by Ben10do** [rednex/rgbds#197]
As we've worked to add features and fix bugs in RGBDS, we've occasionally made backwards-incompatible changes that affect more projects than we'd anticipated.

While the outcomes of #136 and #190 have been positive, leading to the well-defined implementation of linkerscripts and unions, it would be good to catch these cases before they become a problem. This would allow us to make backwards-compatible amends, or at least alert their authors and publicise the compatibility break.

The developers of Swift have made [a list of projects](https://swift.org/source-compatibility/) with which they test new versions of Swift (and scripts to do so), helping them to recognise drastic changes in the language or compiler. I think that it would be beneficial to do something similar for RGBDS, using a script in the repo and/or extra continuous integration tests.

**Comment by AntonioND** [comment]
While this may make sense, for the time being I'm just going to create a new branch so that we can follow this: http://nvie.com/posts/a-successful-git-branching-model/ That way, projects that use this toolchain can point at the `master` branch, and the `develop` branch only catches up with master when a release is going to be made.

**Comment by Ben10do** [comment]
I presume you mean that the other way round, otherwise you'd be better off naming the new branch `stable` 😉

**Comment by AntonioND** [comment]
Oh, yeah, the last sentence is wrong, I meant that master only points at the new develop when a new release is going to be made.

**Comment by AntonioND** [comment]
Fixed via https://github.com/rednex/rgbds/pull/228

If there is another project that could be good as reference, please suggest it.
