### ISSUE TITLE
error: 'minbank' may be used uninitialized in this function

### ISSUE THREAD

**Issue by matthewbauer** [rednex/rgbds#198]
I'm getting this error on GCC 5.4.0:

```
building
build flags: SHELL=/nix/store/jjg5zsfjl35b239f6znp0nfa9775qy2a-bash-4.4-p12/bin/bash
src/asm/asmy.y: warning: 2 shift/reduce conflicts [-Wconflicts-sr]
src/asm/asmy.y: warning: 3 reduce/reduce conflicts [-Wconflicts-rr]
src/asm/asmy.y: In function 'bankrangecheck':
src/asm/asmy.y:60:8: error: 'minbank' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   bank -= minbank;
        ^
cc1: all warnings being treated as errors
make: *** [Makefile:103: src/asm/asmy.o] Error 1
```

full log is available at https://travis-ci.org/NixOS/nixpkgs/jobs/260513464

**Comment by AntonioND** [comment]
This is a false positive. I guess that the compiler thinks that if the default case in the switch is reached then that line could be executed without a value for minbank, but that could only happen if the section was of type WRAMX (so the default case can't be executed). Anyway, it should be fixed here: https://github.com/rednex/rgbds/commit/8954858bf79a9ad48eacb063d42b47882ede1175
