### ISSUE TITLE
Indentation breaks the compiler

### ISSUE THREAD

**Issue by sc-x** [rednex/rgbds#200]
I'll just keep this super brief - indenting code often leads the compiler to generate erroneous syntax errors, usually indented lines are interpreted as macros.

I'm guessing this is an issue with the tokenizer reading tabs and leading spaces as symbols.

**Comment by SamNChiet** [comment]
Thanks for all the work you do!

**Comment by AntonioND** [comment]
Could you paste a short example of code with this problem? It's pretty hard to know what you're talking about if not...

**Comment by SamNChiet** [comment]
Scratch that.
I think when I ran into this I was indenting sections of code with labels, which I guess are supposed to be unintended anyway. It's a little odd that the error thrown is about macros, but it's ultimately not a huge deal.

Feel free to close this issue!

**Comment by AntonioND** [comment]
Yeah. I was thinking that maybe it wasn't documented, but it is: https://github.com/rednex/rgbds/blob/840ddcecd2965a2b7301944e5bf47d01a1fba353/src/asm/rgbasm.5#L231

However, it may be worth improving the message. I'll take a look at the parser to see if it's an easy fix or not.

**Comment by SamNChiet** [comment]
The documentation link on the main page just linked back to the github repo for me when I checked.

**Comment by AntonioND** [comment]
The link in this repo should point to this other repo https://github.com/rednex/rednex.github.io which points at https://rednex.github.io/ . Which may be a bit confusing, I agree.

**Comment by tobiasvl** [comment]
GitHub does support keeping GitHub Pages for a repo in the _same_ repo as the project, either in a `docs/` subdirectory or even in a different branch called `gh-pages`. That would probably be the least confusing way to do it, although it would change the url to https://rednex.github.com/rgbds.

**Comment by AntonioND** [comment]
I've just moved the documentation to this repository: https://rednex.github.io/rgbds/
