### ISSUE TITLE
[Feature request] BANK()

### ISSUE THREAD

**Issue by yenatch** [rednex/rgbds#203]
Currently you can use `BANK()` on labels, like so:
```asm
Label:
db BANK(Label)
```
In some cases this is used to get the current bank, which could instead be done with no arguments:
```asm
db BANK()
```
It might also be nice to do sections:
```asm
SECTION "Section", ROMX
db BANK("Section")
```
This is a non-essential feature since you can always use a label.

**Comment by aaaaaa123456789** [comment]
If `BANK()` wouldn't play nice with the syntax, `BANK(@)` would also work.

**Comment by AntonioND** [comment]
I'll take a look at how easily this can be implemented. The `BANK(@)` thing should be easy enough to do. The section names are trickier.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/pull/218
