### ISSUE TITLE
[Bug] No error on failing to write output file

### ISSUE THREAD

**Issue by ekimekim** [rednex/rgbds#204]
When giving a path to output the object file to, and this path cannot be written to, the assembler generates no error message and appears to succeed, however the output was silently discarded. I originally discovered this in the case of writing to `foo/bar.o` where `foo/` does not exist, but it seems to happen for any writing error, such as a permissions error or attempting to write to a directory.

Example:

```
$ ls
example.asm
$ cat example.asm 
SECTION "example code", ROM0

Example::
	ret
$ rgbasm -v -o foo/example.o example.asm 
Assembling example.asm
Pass 1...
Pass 2...
Success! 5 lines in 0.00 seconds (152827 lines/minute)
$ ls
example.asm
```

Expected behaviour:

An error message printed (perhaps only with verbose output, however since its a fatal error I'd argue not), compilation aborted and exit with a failure status.

Tested on:

Linux only. `rgbasm` version `0.3.3` (commit 193cc06)

**Comment by AntonioND** [comment]
This is a bit of a pain, there are lots of different functions writing to the file at different parts of the code. I agree that it is a problem and it should output an error and abort, though.

**Comment by ekimekim** [comment]
If it's easier, only reporting errors on fopen (not on each write) would
capture 99% of issues.

**Comment by AntonioND** [comment]
Yes, but if this is going to be fixed it might as well be fixed properly. I think that the best way of fixing this would be to have a buffer that grows as more space is needed and that is only written to the file when the assembly process ends. That means that all fwrite() and similar functions have to be replaced by new internal functions, though.

**Comment by AntonioND** [comment]
This commit adds a small check when opening a file, but it's still needed to check at every other write call. https://github.com/rednex/rgbds/commit/c8fa7998838199d1f1d3ae7ec94fcad58515fa02

**Comment by ISSOtm** [comment]
Fixed, apparently.
```
issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgbasm -V
rgbasm v0.3.9-29-ga40d599
issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgbasm -o /root/a.o a.asm
ERROR: a.asm(3):
    Couldn't write file '/root/a.o'

5 issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgblink -V               
rgblink v0.3.9-29-ga40d599
issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgblink -o /root/out.gb a.o
error: Could not open file "/root/out.gb": Permission denied
1 issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgbgfx -V                         
rgbgfx v0.3.9-29-ga40d599
issotm@sheik-kitty tmp.jzQPA519ga% ~/rgbds/rgbgfx -o /root/test ~/world_of_light/src/res/black.png 
error: Opening output file '/root/test' failed: Permission denied
```
