### ISSUE TITLE
[Feature request] Have POPS also restore local label scope

### ISSUE THREAD

**Issue by ekimekim** [rednex/rgbds#205]
The rationale is for declaring sections in macros, I want to be able to do:
```
.foo
    MyMacro
    jr z, .foo
```
while in MyMacro defining a new section:
```
MyMacro: MACRO
PUSHS
SECTION "MyMacroData\@", ROMX
MyMacroData\@:
    db 1,2,3,4
POPS
    ; Do something with MyMacroData\@
ENDM
```

Currently, if I attempt this, my code before the macro cannot use local labels created after the macro and vice versa.

My real-world example of this is a "DebugMsg" macro for use with BGB emulator, which lets you define a debug message either inline or pointing at a message. Currently I'm doing things inline but it causes problems where code will be too big for eg. `jr` instructions to work if debug messages are enabled. I'd like to be able to define the messages off in some arbitrary floating section and reference them instead, but this is very difficult without the ability to define new sections inside the macro body safely.

**Comment by AntonioND** [comment]
To be fair, this is more a bug than a feature request, I'd say...

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/pull/220

**Comment by ekimekim** [comment]
Just updated my debug code to use this and it works great, thanks!
