### ISSUE TITLE
Spurious compiler warning when using DB,etc without args

### ISSUE THREAD

**Issue by ekimekim** [rednex/rgbds#210]
The following code:

```
SECTION "Data", WRAM0
MyByte:
  db
```

is suggested by the docs as an idiomatic way of doing RAM definitions:

> Declaring variables in a RAM section
> DS allocates a number of bytes.  The content is undefined.  This is the preferred method of allo‐
> cationg space in a RAM section.  You can, however, use DB, DW and DL without any arguments
> instead.

However, due to https://github.com/rednex/rgbds/issues/208, this code now produces a compiler warning:
> Empty entry in list of 8-bit elements (treated as 0).

I understand this warning was added to capture cases such as `DB 1,,2` or `DB 1,2,`, but I think a bare `DB` should be a special case, as otherwise there is no alternative when declaring variables in RAM sections except `DS 1`, etc.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/pull/211
