### ISSUE TITLE
Define SRAM bank count limit

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#217]
Right now `rgbasm` and `rgblink` have different values for the number of available SRAM banks. I personally prefer to set this to 16, as that's the max used by an actual game, but I'd like to know what others think.

https://github.com/rednex/rgbds/blob/8954858bf79a9ad48eacb063d42b47882ede1175/src/asm/asmy.y#L34-L38

https://github.com/rednex/rgbds/blob/8954858bf79a9ad48eacb063d42b47882ede1175/include/link/assign.h#L15

**Comment by AntonioND** [comment]
Considering that the current limit is 16 banks because of the linker, and that not a single officially released game contains more than 16 banks, I'm going to set the limit in the assembler to 16 banks as well. If someone complains, it can always be incremented...

**Comment by aaaaaa123456789** [comment]
No known current mapper has more than four bits for SRAM banks, so this value should be good.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/commit/8521e45edcda6645a3ab047dc7a0372d19a27ba2
