### ISSUE TITLE
v0.3.4 broke WRAMX linking

### ISSUE THREAD

**Issue by mid-kid** [rednex/rgbds#224]
In https://github.com/pret/pokecrystal, we've been experiencing a problem with linking the wram sections with people using rgbds v0.3.4.
The error we see is as follows:
```
error: Unable to place 'WRAM 1' (WRAMX section) at $D000 in bank $00
```

Nobody has an idea of what it really means, so it's pretty hard to figure out what is wrong. I've tried a variety of things, ranging from modifying the linker file, re-arranging sections, or reverting some commits in rgbds. At best, I've gotten the following error, when `WRAMX 1` is omitted from the linker file:
```
error: getrealbankfrominternalbank: Unknown bank -1
```

I've been unable to reproduce this in smaller projects, and similarly unsuccessful in pinpointing what triggers these errors. The best I can give you is that commit https://github.com/rednex/rgbds/commit/959bfe2a9dd5ee8d30f740c557502f7d9cd2efff caused the `getrealbankfrominternalbank` error and commit https://github.com/rednex/rgbds/commit/975200834ecefd2c05b5f7b292172d222fa751e8 changed it to the `Unable to place` error.

However, from my observations, I believe this is probably an internal rgbds problem, and if not, should be documented in the changelog regardless.

Thank you for your time.

**Comment by AntonioND** [comment]
I think I have an idea of what may be broken, I'll take a look at it now.

**Comment by AntonioND** [comment]
It was actually pretty easy to reproduce:

**test.asm**
```
SECTION "WRAMX 1", WRAMX
MyLabel: DS 1
```

**ls.link**
```
WRAMX 1
  "WRAMX 1"
```

**Command line**
`./rgbasm -o test.o test.asm ; ./rgblink -o test.gb -l ls.link test.o`

It is caused by the linkerscript, it doesn't happen without it. That's why you didn't reproduce it with small projects.

**Comment by AntonioND** [comment]
I've just pushed https://github.com/rednex/rgbds/commit/b07a8501d6b3a4fd75a73c26637814bde9bedb98

In my PC now I can compile pokecrystal, it was failing before with the symptoms that you mentioned. Could you confirm that this works for you?

**Comment by mid-kid** [comment]
That's very weird. I tried doing the same thing as you did with the linker script to reproduce it, but it didn't work. Might not have added the correct version to my PATH, maybe.

In any case, your fix right there has worked for me, and apparently for Travis. Many thanks!

**Comment by AntonioND** [comment]
No problem.
