### ISSUE TITLE
Prefer snprintf to strncpy

### ISSUE THREAD

**Issue by bentley** [rednex/rgbds#227]
I’m not a fan of strncpy here. strncpy is designed to output to fixed‐width buffers, not C strings (hence its weird null termination behavior). In this case it happens to work correctly due to the length check, but for style reasons I would rather use snprintf. Especially in this case, where it shortens the code a bit.

Diff is attached. (I would open a pull request, but if I made a fork to do so, it would replace the current redirect from bentley/rgbds to rednex/rgbds.)

[snprintf.txt](https://github.com/rednex/rgbds/files/1669621/snprintf.txt)

**Comment by AntonioND** [comment]
Fixed here https://github.com/rednex/rgbds/commit/abeca2d3050957879a9e388dd697610c65469b91
