### ISSUE TITLE
[Feature request] Explicit instruction forms

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#230]
This isn't as scary as the title suggests. While I don't know anyone who has an immediate need for this, it seems simple enough to suggest it in advance.

This idea affects two instructions: `ld` and `jr`. For the former, `ld a, [$ff00]` will always reduce to a two-byte form, and there is no way of telling the assembler you want the three-byte form without deliberately obfuscating the address. For `jr`, there is no way to tell the assembler that the argument represents an actual byte offset (i.e., the actual argument to `jr`); instead, the assembler will always calculate the offset based on the given target address.

While these optimizations are overall helpful, there are a couple of corner cases, typically involving self-modifying code, under which they would be undesirable. Therefore I propose two new instructions that are explicit forms of `ld` and `jr`, not performing any optimizations over their arguments.

For instance, assuming said instructions were called `ld!` and `jr!` (I know the names aren't ideal; I picked them here to highlight the instructions), this code would assemble as commented:

```
  ld a, [$ff00]    ; F0 00
  ld! a, [$ff00]   ; FA 00 FF
  jr .test         ; 18 06 - notice the location of test
  ld a, [$1234]    ; FA 34 12
  ld! a, [$1234]   ; FA 34 12 - no change from above
.test
  jr! nc, -10      ; 30 F6 - will jump to the jr .test instruction
  jr! $02          ; 18 02 - will skip the next instruction
  jr! .test        ; invalid, or truncates .test to 8 bits (like ld a, .test would)
```

While I don't have any immediate use for this, I doubt it would be too hard to implement, considering these new instructions would be very similar to existing ones.

**Comment by ekimekim** [comment]
+1. I have some code right now where I'm trying to `jr` from one section to another. Both have fixed base addresses but I wasn't able to massage the compiler into letting me `jr` between them directly. My next approach was to calculate the diff manually, but in the absense of a direct `jr DIFF` instruction I had to also encode the instruction manually. This is what the instruction looks like in my code now:
```
db $18, $16 ; jr $18
```
This is obviously not ideal.

**Comment by AntonioND** [comment]
Actually, that shouldn't be too hard to do even now, I'll take a look at it. I remember having that problem some time ago as well.

**Comment by AntonioND** [comment]
There you go: https://github.com/rednex/rgbds/pull/241

**Comment by aaaaaa123456789** [comment]
A partial solution, but certainly helpful in some cases.  
We should probably leave the issue open for whenever you have the time to implement the requested feature, I guess.

**Comment by AntonioND** [comment]
Instead of adding new mnemonics, it makes more sense to be able to disable the optimization of `ld`. For `jr` and `jp` this is not an issue for now because they aren't optimized, let's keep it that way:

https://github.com/rednex/rgbds/issues/243
