### ISSUE TITLE
[Feature request] Line continuations

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#231]
I'm almost certain this has been mentioned before, but I cannot find an issue for it. If there is one, please point it out and close this one.

What I'm asking for is a feature that exists in some form or another in almost any programming language where line breaks matter: indicate that a specific newline character should be ignored.

For instance, consider a long macro that accepts an arbitrary number of data values:

```
  sillymacro $01, $01, $02, $03, $05, $08, $0d, $15, $22, $37, $59, $90, $d9
```

While that example isn't long enough to become unreadable, it should be easy to see how that would certainly happen if the list of values was two or three times as long. It forces a choice of line-wrapping or horizontal scrolling, both of which are confusing and unnecessary.

An effective solution would be to indicate to split the values into multiple lines. In order to do that, the assembler has to know that a certain line break only exists for formatting purposes and should be ignored. A way in which this can be achieved is C-style newline escaping:

```
  sillymacro $01, $01, $02, $03, $05, \
             $08, $0d, $15, $22, $37, \
             $59, $90, $d9
```

...or Visual Basic-style line continuation markers:

```
  sillymacro $01, $01, $02, $03, $05, _
             $08, $0d, $15, $22, $37, _
             $59, $90, $d9
```

Disregarding the exact character used for this purpose, the main differences between both styles are that newline escaping requires the escape character to be the very last character on the line (line continuation markers tolerate trailing whitespace), but line continuation markers are tokens by themselves and cannot occur within other tokens (on the other hand, newline escaping can occur inside a string literal, for example).

Whichever solution is picked, line continuations would certainly make macros with long (read: variable) lists of arguments more usable.

**Comment by Sanqui** [comment]
I'm in favor of `\` at the end of the line.  It'd be great for strings as well.

**Comment by AntonioND** [comment]
For strings you can just split them like:
```
DB "String"
DB " and more string"
```
I don't really like the idea of applying that to strings (or comments), to be honest.

However, in general this would be useful, I agree.

**Comment by aaaaaa123456789** [comment]
The above doesn't apply when the string is an argument to a macro, sadly.

**Comment by AntonioND** [comment]
Fair enough, but for that to work with strings the string has to continue at the start of the line. That's essentially the same as just wrapping the lines in your editor.

**Comment by AntonioND** [comment]
For macro arguments, why not `STRCAT`?
