### ISSUE TITLE
Rgbgfx doesn't handle color yet

### ISSUE THREAD

**Issue by obskyr** [rednex/rgbds#232]
`rgbgfx` is a bit incomplete. Although there's a command line switch to export a palette file from a given PNG, and the documentation mentions "sorting colors from lightest to darkest", in actuality `rgbgfx` doesn't take color into account at all. Instead, it currently [quantizes](https://github.com/rednex/rgbds/blob/1a5c423984ca6cce1cb0b6b2100836bf4aa56e84/src/gfx/makepng.c#L153-L157) colors to the first 4 colors in the palette if the PNG is indexed, and to a preset grayscale palette if truecolor or grayscale. The documentation and [a few comments](https://github.com/rednex/rgbds/blob/1a5c423984ca6cce1cb0b6b2100836bf4aa56e84/src/gfx/makepng.c#L106-L111) suggest that this was meant to be temporary behavior until the much more complicated intended logic had been implemented. It makes sense to implement, too - currently, the palette file output does nothing (except output the preset grayscale palette) for non-indexed images, and truecolor images are often quantized in a way that assigns the same palette index to multiple colors.

There are also other color-related problems that `rgbgfx` doesn't handle properly yet - for example, transparency.

In practice, this means a few features have to be implemented:
* Truecolor and grayscale PNGs need to be analyzed to build a palette from the pixel colors.
* Generated palettes need to be sorted by relative luminance.
* All types of PNGs need to be checked for palettes with too many colors.
* Transparent pixels need to correspond to a color in the palette, as opposed to adding a new one or being thrown away.

All of these features can be implemented in a way that's backwards-compatible with *at least* pokecrystal and [Telefang](https://github.com/telefang/telefang), and with what the documentation states, so implementing / fixing these things shouldn't cause any problems.

I've implemented the missing features on my end, so I'll have a pull request coming in shortly (after a bit of extra polish)!

**Comment by AntonioND** [comment]
Fixed via https://github.com/rednex/rgbds/pull/234
