### ISSUE TITLE
[Feature request] Support linking against a symfile

### ISSUE THREAD

**Issue by Sanqui** [rednex/rgbds#233]
When making a disassembly, it's often very useful to label a routine even if you don't intend on actually including its source code soon.  It proves convenient to write those labels in a symfile done by hand and linking against it.  This allows much faster iteration on partial disassemblies.

Example of a partial ("shim") symfile in my Harvest Moon 3 disassembly: https://github.com/Sanqui/hm3/blob/master/shim.sym

Currently, I'm using a [dead simple Python script](https://github.com/Sanqui/hm3/blob/master/tools/make_shim.py) to turn the symfile into a `.asm` file, creating a section for each label.  I wonder if it would be possible to make `rgblink` link against `.sym` files just as it does against `.o` files.  Alternatively a `rgbsym` or similar could be written to create `.o` files from `.sym` files, but I'm not convinced it's worth separating this feature.

Please let me know your thoughts.  I'm willing to have a stab at implementing this myself.

**Comment by AntonioND** [comment]
I'm not sure about this. If you don't like that workflow, I'd say that you could keep that extra sym file as an independent file and concatenate it to the one generated by rgblink after the linking stage. In the end, what you want is to have all the labels in the same sym file, so I don't see the point in, in short, reading it and then writing to another file.

**Comment by Sanqui** [comment]
Concentrating after the linking stage doesn't let me reference the symbols I define in the symfile from disassembled code... That's sort of the whole point.

**Comment by Sanqui** [comment]
Concentrating after the linking stage doesn't let me reference (call etc.) the symbols I define in the symfile from disassembled code... That's sort of the whole idea of linking **against** the symfile.

**Comment by obskyr** [comment]
@AntonioND The benefit wouldn't be adding extra symbols to the final symbol file, it'd be being able to link to labels you don't have in your assembly yet.

For example, consider the following case from a disassembly project:

```asm
    call $0C36 ; Haven't disassembled this decompression routine yet
```

To keep your disassembly readable, you might want to switch that address out for a label, despite not having disassembled that routine yet. In that case, you currently have to do something like this:

```asm
    call Decompress
```
```asm
; Elsewhere, perhaps in a different file...
SECTION "Shim for decompression routine", ROM0[$0C36]
Decompress::
```

That shim is 100% boilerplate and very verbose, so an easier alternative would be to have a symbol file in which you put a line like:

```
00:0C48 Decompress
```

Then you'd just run something along the lines of `rgblink -S undisassembled.sym -O base_rom.gbc -o output.rom thing.o thing2.o` and you'd both have readable code *and* no linker errors.

**Comment by ISSOtm** [comment]
I'd like to bring some insight to this (and also bump, lol), since I'm currently starting such a disasm for/with pret.
We're aiming at having one giant section per bank, or at least per "block" (e.g. two contiguous functions with a similar purpose, eg. `CopyBytes` and `CopyFar`). The problem that Sanqui's shims resolve is that unless a function, or worse, a block of data, has been fully disassembled, the next ones require a section as well, in order to be placed correctly. This means that at some point of the development, we need to go back and remove all these sections.
Thus, I definitely support this request.

As to how the functionality should be implemented, I was rather thinking of letting RGBASM parse SYM files (perhaps using a specific command-line switch?), and output .o files. That would allow to mix them seamlessly into the build process (defining an additional Makefile rule to generate `.o` files), and also replace seamlessly a shim file with its disassembled counterpart.
Example: initially, I'd have `copy.sym` with the location of labels `CopyBytes` and `CopyFar`, and once I start disassembling them, I replace the file with `copy.asm` with the proper code.

**Comment by aaaaaa123456789** [comment]
If this was to be done, I'd recommend using a completely separate tool to parse .sym files and generate .o files, given that this tool would have absolutely nothing in common with rgbasm other than the .o file format (which is shared across tools already).

**Comment by AntonioND** [comment]
I agree with @aaaaaa123456789 that it doesn't make much sense...

`rgbasm` is enough of a mess as it is right now, and this is easy to do with an external tool as the one that @Sanqui is already using to create an asm file from a sym file. Not to mention code complexity. That script is 36 lines long, I'm pretty sure that the equivalent code in C would be longer and more complex (so more prone to bugs).

**Comment by ISSOtm** [comment]
Makes sense. I've updated the tool to support the -w, -t and -d options (to be compatible with the similar RGBLINK options, and it's only 75 lines long (with a few blank lines). The equivalent C code wouldn't be very long, tbh.

**Comment by ISSOtm** [comment]
Since #417 has been merged, I believe it's possible to have a script output a `SECTION` for each symbol in the sym file, and assemble that file. Does that sound reasonable?

**Comment by aaaaaa123456789** [comment]
While that seems like a poor man's solution, it would work. I'm starting to think it would be nice to have some sort of `rgbobj` tool to generate this kind of "special" object files (as well as any other special kind that would arise, such as, say, an object file directly from a binary file)...

**Comment by ISSOtm** [comment]
I think RGBASM is a "good enough" solution at least for now—it has `INCBIN` and other features that allow using it as a fairly flexible object file generator. Unless a more complex need arises, I'm going to consider this done (and besides, `rgbobj` would be better suited for a separate issue, anyways).
