### ISSUE TITLE
PRINTT not working in files with Mac line endings

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#236]
I've just realized that `PRINTT` does nothing when I save my source files with Mac line endings `"\r"`. I don't know if this happens in an actual Mac or if it only happens in my Linux PC. This doesn't happen with Windows `"\r\n"` or UNIX `"\n"` line endings.

If it only happens in my machine, I think I will just ignore the problem because `"\n"` is a saner convention when using UNIX-like tools.

@Ben10do could you check this?

**Comment by Ben10do** [comment]
These days, macOS uses LF (as it’s based on UNIX). As a result, I imagine I’ll get the same behaviour if I try this on my Mac. I’ll give it a go anyway, when I get a chance.

Only the pre-millennium “Classic” Mac OS uses CR, so I’d be *very* surprised if people are still using CR line endings.

**Comment by AntonioND** [comment]
Heh, turns out it's far more simple than that... The parser doesn't know how to end commands in files that only have CR characters... Could you check that? :P
```
SECTION "Test", ROM0
; This is a harmless comment
PRINTT "This is a test\n"
```

**Comment by Ben10do** [comment]
Aha, it looks like that harmless comment does cause some problems! 😆

[We seem to be only checking for `\n` (or `\0`) to terminate comments](https://github.com/rednex/rgbds/blob/master/src/asm/lexer.c#L186-L188), which corresponds to LF on modern Macs.

If you do want to fix it, it'd probably be best to convert either CR or CRLF to LF early on (e.g. before being passed to the parser, if that's possible?), as I'm sure there'll be plenty of other places where we'll just be checking for `\n`.

However, I see no problem with leaving out support for CR-encoded files; as you say, this is a UNIX-style tool, and macOS is a UNIX-based OS these days.

Problems would only occur in practice if anyone tries to open really old files that were created on Mac OS 9, but I've no idea how many such files were made (and haven't been converted to LF in the last eighteen years), and I imagine other UNIX-y tools would similarly choke on them.

**Comment by AntonioND** [comment]
So the problem is that the conversion of line ending characters is done at the same time as removing the comments. That's why this problem only happens with comments but not with actual code. It's super easy to fix, so we'll keep supporting CR line endings. :P

I've split the loop into 2 loops, one to convert line endings and another one to remove comments... and I've found out an obscure syntax for comments that nobody uses, for more info, check that PR. :P

**Comment by AntonioND** [comment]
Fixed here: https://github.com/rednex/rgbds/commit/3bebedf1f810c3d6149b59b75923bf4ee2442696
