### ISSUE TITLE
Make the documentation prettier

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#247]
I've pushed commit https://github.com/rednex/rgbds/commit/0e0e12a769f226c95d282c84134b3ac414f8d266 that adds a css file [1] that makes the html documentation [2] much prettier than it was before. However, I'm sure that someone can improve it.

[1] http://mdocml.bsd.lv/cgi-bin/cvsweb/mandoc.css
[2] https://rednex.github.io/rgbds/

**Comment by doeg** [comment]
I'd be happy to take this one if you're looking for contributors! :D

**Comment by AntonioND** [comment]
Just a reminder in case you hadn't noticed. The html files are auto-generated (except for the main menu) with `make wwwman`, so you shouldn't modify them! You can only modify the .css file, the index .html file, and the .1, .5, etc, files.

**Comment by doeg** [comment]
@AntonioND thanks for the heads up! I'm planning to work on this issue this weekend. 

Did you have anything specific in mind that I should focus on? :)

**Comment by AntonioND** [comment]
Hmmm... Not really, I just think that the current design can be improved. It's better than what there was before adding the css file, but the current one isn't that great either. However, I'm not sure about how flexible this system is, so it could be that the end result isn't that different from what we have now.

I don't think you should spend too much time on the first iteration. This is completely subjective, so I wouldn't like to see you work for a long time just to say no to the end result. If you have done something similar in the past, you could put a link here.

This has a very low priority. Even if you can't do it this weekend, it's fine.

**Comment by ISSOtm** [comment]
Fixed as of 0.4.0, both with the updating of the `mandoc.css` style sheet, and the adding of a custom `rgbds.css` one.
