### ISSUE TITLE
Mac Install Error: SHA256 mismatch

### ISSUE THREAD

**Issue by marbuljon** [rednex/rgbds#249]
Upon trying to install rgbds on a Mac I get this:

==> Installing dependencies for rgbds: libpng
==> Installing rgbds dependency: libpng
==> Downloading https://downloads.sourceforge.net/libpng/libpng-1.6.34.tar.xz
==> Downloading from https://downloads.sourceforge.net/#!/libpng/libpng-1.6.34.t
######################################################################### 100.0%
Error: SHA256 mismatch
Expected: 2f1e960d92ce3b3abd03d06dfec9637dfbd22febf107a536b44f7a47c60659f6
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/(USERNAME)/Library/Caches/Homebrew/libpng-1.6.34.tar.xz
To retry an incomplete download, remove the file above.

—————
I removed the file and retried, but get the same error.

**Comment by bentley** [comment]
Sounds like a problem you should report to the Homebrew folks.

**Comment by Ben10do** [comment]
Indeed, this looks like a problem with Homebrew’s libpng download.

As this is before it even gets to downloading RGBDS itself, I don’t think there’s a lot we can do about this, I’m afraid.

`libpng` is hardly an obscure library, so I’m sure it’ll be fixed promptly 😊

**Comment by marbuljon** [comment]
Hey, thanks guys, sorry for the trouble haha. After a few hours I suddenly had the brilliant idea to download libpng-1.6.34.tar.xz from some external site somewhere and drag it into the folder separately, and now installing rgbds worked!
