### ISSUE TITLE
Missing documentation on charmap feature

### ISSUE THREAD

**Issue by mid-kid** [rednex/rgbds#250]
`charmap` doesn't seem to be documented in `rgbds(5)`, resulting in it being a pretty obscure feature.
While it's pretty self-explanatory for the most part, it should be documented somewhere, as it's otherwise unknown to new users and unclear whether it's a builtin or a user-defined macro.

**Comment by AntonioND** [comment]
Yeah, this should be documented. I intend to create another release over the next few days, this should be fixed in that release.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/commit/483a63156b64370638574a42916bf61505315d3a
