### ISSUE TITLE
[Feature request] Binary literals

### ISSUE THREAD

**Issue by obskyr** [rednex/rgbds#253]
Having to write bit fields and masks in hex isn't too much fun. It'd be nice if RGBDS had binary literals. For example, `ld a, $99` could be written `ld a, 0b10011001` (`0b` prefix from countless other languages).

**Comment by AntonioND** [comment]
This is already there:
```

    Hexadecimal: $0123456789ABCDEF. Case-insensitive
    Decimal: 0123456789
    Octal: &01234567
    Binary: %01
    Fixedpoint (16.16): 01234.56789
    Character constant: "ABYZ"
    Gameboy graphics: `0123
```
https://rednex.github.io/rgbds/rgbasm.5.html#Integer_and_Boolean_expressions

**Comment by obskyr** [comment]
Ah, there we go. "Literals" wasn't the phrasing to search for in the docs, "numeric formats" was. Thanks.

**Comment by AntonioND** [comment]
Well, it's not something that is normally used. In my case I just forget the prefix...
