### ISSUE TITLE
[Feature proposal] align keyword within sections

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#254]
I'm calling this a "feature proposal" and not an actual request because I don't have any immediate need for it; it's just an idea that came to me, so I'm putting it here to see what others think.

The key behind the implementation is as follows:

* The assembler simply enforces alignment with respect to the beginning of the section. Since this only requires keeping track of the current offset within the section, it is well within the possibilities of the assembler.
* The linker verifies that the alignment constraints are followed.

**Syntax:**

This would require a pseudo-instruction (like `ds`) to be used at the point where alignment is required. I'd suggest just `align <expression>`, to make it similar to linkerscripts. Of course, `<expression>` should be an assembly-time constant, and it should be checked for a reasonable range of values.

This instruction would be available for sections of any type.

**Assembler behavior:**

The assembler would simply insert padding bytes to fulfill the alignment instruction with respect to the beginning of the section. In other words, assuming there was some symbol defined at the beginning of the current section called `SectionStart`, the `align` instruction could be replaced by this macro:

```
align: MACRO
  ds (SectionStart - @) & ((1 << (\1)) - 1)
ENDM
```

The assembler would also record, as part of the section attributes, the maximum alignment requirement it encounters for each section. (I don't know much about how the object file format works, but I assume there are fields for attributes such as the bank number and base address. The maximum alignment requirement would be another such attribute.) 
Note that this means that the assembler wouldn't be required to actually align the section, just record the requested alignment. This value is separate from whatever is indicated as an `ALIGN` requirement in the section header.

**Linker behavior:**

There are multiple possible ways the linker can handle these alignment requirements. Since all of the following options essentially build on top of each other, the best idea would be to select one of these options at link time via a linker flag, such as `-a fail` or `-a warn`. The options I can think of are as follows:

* `none`: ignore the value recorded by the assembler. This would be useful in limited cases (I can think of one or two situations in which it would help, though), but backwards compatible, and most likely trivial to implement.
* `warn`: place sections as usual, ignoring the maximum alignment requirement recorded by the assembler. However, if this results on any section not meeting this requirement, emit a warning. This might be best for (future) disassemblies, for instance.
* `fail`: same as `warn`, but causing a hard failure.
* `default`: I can't really think of a better name for this one. For sections that are truly floating, the linker would assume the maximum alignment recorded as the alignment for that section, as if it had been specified via `ALIGN` in the section header; the same applies to sections in the linkerscript that don't come after an `org` or `align` directive. For other sections, it behaves like `fail`.
* `override`: the most invasive option. Forces all sections to meet the maximum alignment recorded — if the section has a lower alignment requirement specified by `ALIGN`, the one recorded by the assembler takes precedence, and if the section has an explicit base address that doesn't meet the maximum alignment recorded, this address is rounded upwards to meet it.

---

I think this properly deals with the issue of having the linker resize sections (this proposal doesn't require the linker to do that), while enabling the use of intra-section alignment.

**Comment by ISSOtm** [comment]
This could be implemented as part of a larger feature set, which would be specifying an offset in addition to alignment. Intra-section alignment would simply cause the parent section's alignment and offset to be computed such that alignment *is* respected at the keyword's point.

The linker would simply add the offset to each candidate location for the section. Instead of trying `$C000`, `$C010`, `$C020` for `ALIGN[4]`, it would try `$C003`, `$C013`, `$C023` for `ALIGN[4,+3]`. The syntax should look like an offset (so plus or minus sign required before the expression) added to the `ALIGN[]` specification. I prefer `ALIGN[algn,+ofs]` to `ALIGN[algn][+ofs]` because I think the purpose of both is clearer in the former.

I had some use for alignment with offset at some point (I wanted an `ALIGN[8]` block with 1 byte before it), so I think it should be useful.

**Comment by NieDzejkob** [comment]
Make sure `ALIGN[4,-3+4]` gets parsed properly.

**Comment by ISSOtm** [comment]
Hm, since that'd be really complicated, maybe any expression could be allowed (`ALIGN[4,1]`) but the plus/minus sign recommended in documentation?

**Comment by aaaaaa123456789** [comment]
In my experience, some people prefer writing offsets with explicit signs, others without. Why would the manual give opinions on code style, anyway?
