### ISSUE TITLE
Support Multiple Charmaps/Disable Charmap

### ISSUE THREAD

**Issue by RenaKunisaki** [rednex/rgbds#256]
Right now it looks like `charmap` overrides any previous mapping including ASCII. This means you can't have more than one mapping, or use ASCII and a custom map in the same ROM (eg for debug output form emulators). Would be great to have a way to specify which mapping to use for a given string or group of strings.

**Comment by aaaaaa123456789** [comment]
How would you do this?

**Comment by Sanqui** [comment]
One way to do this would be a `setcharmap` directive, which would switch the behavior of `charmap` and `db`.  A disadvantage is that it introduces state.

```
    setcharmap ascii
    charmap "A", $41
    charmap "B", $42
    
    setcharmap game
    charmap "A", $10
    charmap "B", $11
```

```
    setcharmap game
    db "Game string@"
    setcharmap ascii
    db "ASCII encoded string"
```

Then you could make macros such as
```
ascii: MACRO
    setcharmap ascii
    db \1
    setcharmap game
ENDM

    db "regular text"
    ascii "ascii text"
```

**Comment by dbrotz** [comment]
`setcharmap` looks like a good idea to me, but I have some questions.

What about "default charmap" that exists before you use `setcharmap`? How do you return to it after switching? Should we just give it the name "default"?

```
; implicit default charmap
charmap "A", $10
charmap "B", $11

setcharmap other
charmap "A", $20
charmap "B", $21
db "A"

setcharmap default
db "A"
```

Another thing to consider is the state that a new charmap starts off with. Does it inherit the current charmap's mapping or start with some predefined initial mapping (e.g. ASCII)?

**Comment by ISSOtm** [comment]
I would agree with hardcoding the default charmap to `default` (ie. that charmap is implicitly created and loaded by the assembler when beginning assemby).

I think creating a new charmap should inherit from the current one, that way if you want to base it off the default mappings you simply do `setcharmap default` beforehand, and it allows making "base" charmaps that deduplicate some charmaps' common parts.

**Comment by dbrotz** [comment]
That sounds good to me. Another thought I just had is that we might want to distinguish between creating a new charmap and switching to an existing one. The benefit is that it might help catch errors where someone thinks they're creating a charmap but they're switching to an existing one or vice versa. The downside is that there would be more directives to remember.

**Comment by dbrotz** [comment]
Also, I don't think my suggestion of "default" is the best idea. It could be confusing because it sounds like it would be the charmap that the assembler begins with, without any changes. "main" would be a better name for it.

**Comment by ISSOtm** [comment]
Well, that charmap *is* the one the assembler begins with, isn't it?

The problem with requiring a `newcharmap` is that it might not be backwards-compatible. Maybe a clearer name for `setcharmap` would be `usecharmap`, or `switchcharmap`? That way it stays akin to what it is now and would just be a context switch.

It does mean that you can keep defining a charmap as you go, which isn't very clean, but that's already what happens with the current system.

Lastly, you can decide to break backwards compatibility in that regard (hopefully in a mild manner), and keep this feature for 0.4.0.

**Comment by dbrotz** [comment]
Yes, but to me, "default" sounds like it's what the assembler begins with, without any modifications by the user. I was thinking that you would start with the "main" charmap already in existance and be able to use `charmap` to alter it, to maintain backward compatibility. You would only use `newcharmap` if you wanted to have more than one charmap.

**Comment by ISSOtm** [comment]
The thing I'm slightly worried about is, to maintain backwards compatibility, the `main` charmap would be special-cased to be modifiable at any time.

**Comment by aaaaaa123456789** [comment]
Under the risk of making suggestions to an issue that already has a pull that closes it, how about this?

1) Define charmaps _as a block_, just like everything else is defined:

    game: CHARMAP ; reusing the keyword shouldn't be a problem, but change it if needed
      charmap "A", $01
      charmap "B", $02
    CEND

2) Use charmaps with `setcharmap`, as proposed; use the assembler's default charmap by passing _no name at all_ (which removes the need to hardcode a name):

      setcharmap game
      db "AB" ; db $01, 02
      setcharmap
      db "AB" ; db $41, 42

Note that the assembler's default charmap would still be modifiable via `charmap` statements. This isn't really a problem for ASCII-users, as they can declare a new empty charmap for ASCII.

This proposal eliminates accidental charmap definitions, as definitions and usage look nothing alike. It still has the problem of state, though.

**Comment by dbrotz** [comment]
I think the charmap definition block could be good. It looks odd that you have to repeat `CHARMAP` on each line inside the block, though. It would still be nice to be able to inherit another charmap somehow, as well.

**Comment by ISSOtm** [comment]
Either the charmap could inherit from the current one (`charmap text` then `jp_text: CHARMAP`), or explicitly inherit from one (`jp_text: CHARMAP text`).

**Comment by dbrotz** [comment]
When I tried putting `charmapdef	: T_LABEL ':' T_POP_CHARMAP` in the grammar, it added an extra shift/reduce conflict.

**Comment by ISSOtm** [comment]
Using a new keyword would make more sense (so as not to overload the `charmap` keyword with too much sense), but it could break code that used such a macro.
