### ISSUE TITLE
rgblink -O creates output file even if it fails to find the overlay file.

### ISSUE THREAD

**Issue by obskyr** [rednex/rgbds#266]
Run `rgblink -O nonexistent_file -o output object1.o object2.o`, and `output` will be created/overwritten (and empty) even if `nonexistent_file` can't be found. `rgblink` should check that it can read from the overlay file before opening the output file.

**Comment by Sanqui** [comment]
Hm, not sure why this isn't working then?

https://github.com/rednex/rgbds/blob/master/src/link/output.c#L120-L125

**Comment by obskyr** [comment]
That does work, but the output file is opened before then.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/commit/e8a16c6f532864886f96684c57f4f211d0126607
