### ISSUE TITLE
[Feature request] DEF for macro arguments

### ISSUE THREAD

**Issue by obskyr** [rednex/rgbds#268]
If there were a `DEF` for macro arguments, you could do things based on how many arguments the caller supplies. This would be very useful for things like data tables or scripting macros for commands with a variable number of arguments. Here's a real use case from a disassembly I'm working on as an example:

```asm
Branch: MACRO
    DB $1C ; Branch is command $1C

    ; Address of value to branch on
    DW \1

    ; Branch address arguments
REPT 256
IF DEF(\2)
    DW \2
    SHIFT
ENDC
ENDR
ENDM
```

```asm
    Branch S_SwordStatus, \
           Scripts_King_02, \
           Scripts_King_03, \
           Scripts_King_04
```

The above would be more natural with a `BREAK`, but is just as useful without. As it stands, you instead have to supply a "number of arguments" argument and use `REPT \2` (for example), which is a bit cumbersome and redundant.

Since arguments are substituted in directly as far as I know, `DEF(\1)` might not be viable (as `\1` will just be substituted), but something like `ARGDEF(1)`, `ARGDEF(2)`, etc. would be just as good.

**Comment by AntonioND** [comment]
Can't you use `_NARG` for this?

**Comment by obskyr** [comment]
You totally can! I had no idea that existed - it's very sparsely documented. Thanks!
