### ISSUE TITLE
Weird behaviour for '@'

### ISSUE THREAD

**Issue by davazp** [rednex/rgbds#273]
Hi,

I have noticed this commit (4d13d57491ab39034af7af05d4e42ea5a14793f2) and the release notes mention that `@` is now offset by 1 byte. The commit message seems to suggest it is fixing it, but the behaviour looks really strange. This program

```asm
SECTION	"start",HOME[$0100]
    nop
    jr @
```

will make a relative jump to a non-instruction, as it falls after `jr`.   It is a known issue as specified in the release..? will be fixed or should the behaviour be clarified?

Thanks!

**Comment by AntonioND** [comment]
This is a known bug that is fixed in the master branch. I intend to create a new release this week with the fix.

**Comment by AntonioND** [comment]
But yeah, in any case, using labels is preferable than hacking the relative jump with '@'.

**Comment by davazp** [comment]
Sure, I was trying to run some existing code. I replaced it with a `.label\@` as it is part of a macro.

Closing this then, thanks for the answer!
