### ISSUE TITLE
[Bug] HEAD breaks pc-relative maths compared to v0.3.6 release

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#275]
Instruction ([source](/pret/pokepinball/blob/master/home/copy.asm#L180)):

    _06D2:
        jp @ + 2

v0.3.6 behavior:

    C3 D5 06 ; intended

HEAD beahvior:

    C3 D4 06 ; branch ends 1 byte early

**Comment by aaaaaa123456789** [comment]
How is `@` = $06d3 intended? That makes no sense; the HEAD behavior seems reasonable.

**Comment by AntonioND** [comment]
Yes, it doesn't make sense, that's the correct behaviour.

**Comment by AntonioND** [comment]
JP is s 3 byte instruction.

**Comment by AntonioND** [comment]
Hopefully this new release 0.3.7 will fix the mess caused by the bug of version 0.3.6.
