### ISSUE TITLE
v0.3.7: RGBFIX fails to compute correct checksums for Spaceworld GS ROMs

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#280]
Using `rgbfix v0.3.7` to generate "correct header" versions of the 1997 Spaceworld Gold/Silver Beta ROMs (such that they would load properly on real hardware) produces incorrect global checksums.  The ROMs will run, however BGB issues a runtime warning upon loading them.  I firmly believe the causal issue was introduced in v0.3.7, as v0.3.6 computes the correct global checksums.

[Reference repository](/pikalaxalt/pokegold-spaceworld/tree/build_more_roms)

**Comment by bentley** [comment]
Probably broken in efae6c7fd28d53746a8442308788f0f12b127cab

**Comment by Ben10do** [comment]
@bentley, you're right, that commit did break it. This was revealed because these ROMs already have a non-zero global checksum. I've submitted a PR that fixes this, #281.
