### ISSUE TITLE
Incorrect instruction compilation

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#291]
I have the instruction `ld c, .tilemapEnd - .tilemap`, which compiles to `ld c, $A0` without warning. Ok.

Then, I have the instruction `ld bc, 8 << 8 | .tilemapEnd - .tilemap`, which should (and used to) compile to `ld bc, $08A0`, but instead compiles to `ld bc, $00A0`.

`.tilemapEnd` is at `1:4809`, and `.tilemap` is at `1:4769`, and are defined in the same file (and same section) as both `ld` instructions mentioned above. Not sure what's happening here, the emitted instruction changed while I was editing some other code in the file. My hunch is that it's related to crossing a page boundary?

[EDIT] `ld bc, 8 << 8 | (.tilemapEnd - .tilemap)` and `ld bc, 8 << 8 + .tilemapEnd - .tilemap` compile correctly, but `ld bc, .tilemapEnd - .tilemap | 8 << 8` compiles to `ld bc, $F8A0`. Maybe it's a priority issue? I'm really unsure.

**Comment by AntonioND** [comment]
It's hard to say with so little information. Have you tried simply using parenthesis? There are some problems regarding priority of operands when labels are involved.

**Comment by ISSOtm** [comment]
Yep, as I wrote below, parentheses fixed the issue, apparently. ...It doesn't make a lot of sense though. I was expecting C operand priority (thus `|` be last), but apparently that's not what's happening.

**Comment by AntonioND** [comment]
Subtracting labels is a tricky thing, so I would expect that to happen first (there are some checks, you can't subtract two relative labels in 2 different sections). The other operations... no idea. I guess that this check messes with the priority order.

**Comment by ISSOtm** [comment]
Seems the same as #255?

**Comment by AntonioND** [comment]
It is indeed.

**Comment by ISSOtm** [comment]
As per #311, this is fixed.
