### ISSUE TITLE
[Feature request] Link time asserts

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#292]
Since the last comment on #202 depends on this issue existing, I'm going to post this now.

Asserts are validations performed while the software builds; passing validations result in nothing, but failing ones result in a build failure. This is useful because it allows programmers to optimize based on preconditions that are currently true, while ensuring that those preconditions are still true later when the software is built.

Consider the following hypothetical example:

```
  ld a, CONSTANT_FOO
  ld [wSomewhere], a
  ld a, CONSTANT_BAR
  ld [wSomewhereElse], a
```

Now, assume that `CONSTANT_BAR` happens to be `CONSTANT_FOO + 1`. That `ld a, CONSTANT_BAR` line can be optimized out to `inc a`, saving one byte and one CPU cycle. However, this would easily break if someone changed the values of `CONSTANT_FOO` or `CONSTANT_BAR` somewhere down the road. The way to assure that this doesn't happen is to make the toolchain enforce it, like so:

```
  ld a, CONSTANT_FOO
  ld [wSomewhere], a
  assert CONSTANT_BAR == (CONSTANT_FOO + 1)
  inc a
  ld [wSomewhereElse], a
```

This assertion serves a double purpose of documenting what's going on (since that `inc a` doesn't make much sense otherwise) and ensuring that the code doesn't suddenly break due to someone changing the values of the constants — if that happened, the assertion would fail, and there would be a build error preventing the software from building until whoever made the change fixed the code.

Now, this kind of compile-time assertion can be implemented through macros. We've been using this macro in Prism for a while:

```
assert: MACRO
	if !(\1)
		if _NARG > 1
			fail \2
		else
			fail "Assertion failed: \1"
		endc
	endc
ENDM
```

However, since this macro requires evaluating the asserted expression as part of an `if` statement, it must be fully evaluated at assembly time (i.e., by rgbasm), forbidding the use of link-time-evaluated expressions (e.g., expressions containing symbols not resolvable by rgbasm).

What I'm requesting, then, are assertions that can be checked at link time (they could be checked at assembly time too, if rgbasm can fully evaluate them), which would enable the use of linked-in symbols in asserted expressions, thus allowing programmers to enforce constraints on their values at link time. This would most likely require an update to the object file format, as it would need to encode these assertions somehow, along with information regarding their location and/or a failure message (so rgblink can print a meaningful error when they fail).

While I've posted repeatedly my opposition to link-time resizing (including any form of conditional resizing) of sections, assertions would not imply any such thing, since passed validations don't result in any output at all. The output of the `assert CONSTANT_BAR == (CONSTANT_FOO + 1)` line above should be nothing at all (i.e., zero bytes) if the assertion passes.

**Comment by pinobatch** [comment]
ca65 can make link-time assertions that ld65 evaluates, so this could be considered "feature parity" with other tools used for indie development of games for Nintendo retro consoles.

**Comment by NieDzejkob** [comment]
First of all, I would like to propose a separate pseudoop, `warnif`, that doesn't stop the linking process. This feature could then also be used internally by rgbds for warnings such as "This `ld` can be an `ldh`", although at a considerable increase in object file size.

I can see a few ways of making the format support these features. For example, the assertions could be emitted as a special type of patches:

```
--- a/src/rgbds.5
+++ b/src/rgbds.5
@@ -116,12 +116,20 @@ REPT NumberOfSections
                                  ; 1 = little endian WORD patch.
                                  ; 2 = little endian LONG patch.
                                  ; 3 = JR offset value BYTE patch.
+                                 ; 4 = assertion - error if expression is non-zero
+                                 ; 5 = warn if expression is non-zero

             LONG    RPNSize      ; Size of the buffer with the RPN.
                                  ; expression.

             BYTE    RPN[RPNSize] ; RPN expression. Definition below.

+            IF      Type >= 4    ; assert or warnif
+
+                STRING  ErrorMessage ; The message to print if the condition is met.
+
+            ENDC
+
         ENDR

     ENDC
```

One significant disadvantage of this implementation is that assertions can't be used in RAM sections, and there's nothing inherently wrong about such an assertion.

It would also be possible to store the data separately:

```
--- a/src/rgbds.5
+++ b/src/rgbds.5
@@ -35,9 +35,10 @@ is a 0‐terminated string of
 .Bd -literal
 ; Header

-BYTE    ID[4]            ; "RGB6"
-LONG    NumberOfSymbols  ; The number of symbols used in this file
-LONG    NumberOfSections ; The number of sections used in this file
+BYTE    ID[4]                 ; "RGB7"
+LONG    NumberOfSymbols       ; The number of symbols used in this file
+LONG    NumberOfSections      ; The number of sections used in this file
+LONG    NumberOfAssertions    ; The number of assertions used in this file

 ; Symbols

@@ -127,6 +128,18 @@ REPT NumberOfSections
     ENDC

 ENDR
+
+; Assertions
+
+REPT NumberOfAssertions
+    STRING  ErrorMessage
+    STRING  SourceFile
+    LONG    Line
+    BYTE    Type ; 0 = assert
+                 ; 1 = warnif
+    LONG    RPNSize
+    BYTE    RPN[RPNSize]
+ENDR
 .Ed
 .Ss RPN DATA
 Expressions in the object file are stored as RPN.
```

Obviously, this approach would require a version bump. I don't know how big of a deal this is.

**Comment by aaaaaa123456789** [comment]
Is that basically a non-erroring version of an assert?

**Comment by NieDzejkob** [comment]
Yes, that's exactly my intention. Do you have a better idea for the name?

**Comment by aaaaaa123456789** [comment]
My main complaint is that asserts are typically written as tests that should _pass_ (the assertion fails if the condition is false), but your `warnif` idea is written as a test that should _fail_ (you get a warning if the condition is true).

Non-fatal asserts can be useful, but it would probably be a better idea to name them and write them so that you'd get a warning if the test fails.

**Comment by NieDzejkob** [comment]
I have just noticed that there is another, unintended difference in semantics: for `assert`, the user expects the condition to be true, while `warnif` would be used when the condition should be false. As such, I believe `warnassert` would be a better name, even if only temporary. Also, the linker should warn/error if the expression evaluates to *zero*.

**Comment by pinobatch** [comment]
The [syntax that ca65 uses](https://cc65.github.io/doc/ca65.html#ss11.6) is

    .assert condition, severity, message

where `condition` is a numeric expression that triggers the assertion if zero, `message` is a string expression, and `severity` is `error` to stop linking (or stop assembly if the expression can be evaluated at assembly time) or `warn` to only print the message. If RGBASM went this route, something to the following effect would implement the use case of #202:

    assert bank(foo) == bank(bar), error, "cross-bank call"
