### ISSUE TITLE
Incorrect STRLEN

### ISSUE THREAD

**Issue by Pokeglitch** [rednex/rgbds#297]
STRLEN() returns the wrong value for "NIDORAN♂".  It appears to return 10 instead of 8.  Maybe it is based on the byte length rather than the char length?

**Comment by aaaaaa123456789** [comment]
Since some legacy code might rely on the byte count for something, maybe it would be worth it to introduce a new function that returns the number of UTF-8 codepoints. Or even the number of charmap codepoints, if it can somehow determine that.
