### ISSUE TITLE
The documentation for OPT is a clusterfuck

### ISSUE THREAD

**Issue by NieDzejkob** [rednex/rgbds#298]
[`rgbasm(5)`](https://rednex.github.io/rgbds/rgbasm.5.html#OPT) tells us that

```
The options that OPT can modify are currently: b, e and g.
```

I decided to check [`rgbasm(1)`](https://rednex.github.io/rgbds/rgbasm.1.html), but I couldn't find the `e` option. After a quick grep and a minute of head scratching on the yacc syntax, I've found the [code responsible for this directive](https://github.com/rednex/rgbds/blob/e2b4554a5c933eaebeb394d9057a6abcd68ac3e7/src/asm/main.c#L124), which supports `b`, `g`, and... `z`, which also doesn't exist as a commandline option. After reading some more source code, I've deduced that it sets the same variable as the `-p` commandline parameter -- the pad value, which is also internally called the fill value.

I think the character used to trigger this option should be changed from `z` to `p`, and the behavior documented.

**Comment by ISSOtm** [comment]
Proposition: add `p` that aliases `z`, and deprecate `z`.

**Comment by NieDzejkob** [comment]
Yeah, sounds right.
