### ISSUE TITLE
Take assembly source code on standard input

### ISSUE THREAD

**Issue by pinobatch** [rednex/rgbds#305]
I wrote a preprocessor that produces RGBASM input on standard output. It'd be more convenient if RGBASM could accept input on standard input, so that I could pipe the preprocessor's output into RGBASM without having to worry about deleting a temporary file.

    # This works
    tools/preprocessor.py src.z80 > tmp && rgbasm tmp
    
    # These work with as (GNU Binutils assembler) but not rgbasm
    tools/preprocessor.py src.z80 | rgbasm
    tools/preprocessor.py src.z80 | rgbasm -

If it matters, the preprocessor is [bgrdedent.py](https://github.com/pinobatch/240p-test-mini/blob/master/gameboy/tools/bgrdedent.py) from 144p Test Suite. If you don't have a preprocessor handy, you can use `cat` for testing this enhancement.

**Comment by NieDzejkob** [comment]
In the meantime, use `/dev/fd/0`

**Comment by pinobatch** [comment]
So that my build process can accommodate my collaborators who use Microsoft Windows, what is the Windows counterpart to `/dev/fd/0`?

**Comment by aaaaaa123456789** [comment]
Many tools accept `-` as a special imput filename for this case; this would certainly be useful.

@pinobatch I believe the equivalent is `CON`.
