### ISSUE TITLE
Take standard long options

### ISSUE THREAD

**Issue by pinobatch** [rednex/rgbds#306]
When I do `rgbasm --help` or `rgbasm --version`, I get this:

    rgbasm: invalid option -- '-'

Even if only `--help` and `--version` are hardcoded, and no other long options are supported, that would improve integration with long-time CLI users' muscle memory.

**Comment by bentley** [comment]
Long‐time CLI users would know that long options interfaces are literally nonstandard by definition (not part of POSIX), that many command‐line applications don’t support them, and that the output across programs varies so much as to be annoying (less than a screenful? multiple screenfuls so I need `| more`? multiple screenfuls on stderr so I need `2>&1 | more`?).

A better instinct is to check first for a manpage, which also varies across programs but does always have at least a synopsis section akin to usage and starts out in a pager.

In any case, in rgbasm getopt errors result in the usage being printed to standard error anyway. I don’t see what benefit --help would provide over both the manpage and the existing usage output.

**Comment by ISSOtm** [comment]
As part of enhancing #405 to allow RGBASM to be passed `-M` even without `-o`, I would like to support long options similar to GCC, which would be `-MT` and/or `-MQ` (override the dependency target).
`-MP` would also be nice to have (phony target added to all dependencies besides the main file).
