### ISSUE TITLE
Don't pad binaries with rgblink

### ISSUE THREAD

**Issue by mid-kid** [rednex/rgbds#307]
I'm trying to use rgblink to link a small binary containing some data that was pre-processed using rgbds macros. This file is then passed through another program before finally being INCBINned in the final ROM.

The only problem to this method is that rgblink insists on padding the binary to 16K. It'd be nice to have an option to disable this padding, or have rgbfix handle padding to 16K boundaries instead.

**Comment by AntonioND** [comment]
As far as rgblink knows, all banks are always 16K and it just outputs blocks of 16K. It simply allocates space for all banks at the beginning and then starts filling them up. This behaviour would mean that it has to keep track of the top used address of each bank and, when writing the last bank, ignore the padding. It feels a bit weird to me, to be honest.

**Comment by aaaaaa123456789** [comment]
I've run into this use case too, and we eventually had to simply use a different tool to generate the files in question.

The issue arises from the fact that the target file is _not a ROM_; rgbds is being used as a way of generating arbitrary binary files for various reasons (typically files that later do get included in the ROM). There are many legitimate uses of the toolchain for this purpose, but under the current state of the toolchain, they generally require weird hacks to calculate the effective size of the file and truncate it post-linking.

If an option enabling this behavior is ever added (which it should be, if it is reasonably possible), I'd recommend the following:

* No banking. Treat the input as if it was in small ROM mode (i.e., ROM0 is 32K) and error out if any ROMX sections are defined.
* Don't add any padding for slack space at the end of the bank. Slack space anywhere else should be filled as usual.
* Output a binary file containing the resulting data, which may have any size <= 32K.

**Comment by MineRobber9000** [comment]
Actually I would suggest using the main upstream for that tool, [zzazzdzz/rgbbin](https://github.com/zzazzdzz/rgbbin). My repo was merged into it in zzazzdzz/rgbbin#1
