### ISSUE TITLE
$ and ` considered numbers

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#308]
The characters `$` and `` ` ``, by themselves, are considered numbers by rgbasm. This seems to act as a degenerate case of a hexadecimal number or a GFX number where the number has no digits, and thus has the value zero. (This doesn't happen for `%`, which I assume is special-cased since it's also an operator.)

For instance, the following code:
```
  ld d, $
  ld hl, `
```

...will load 0 into `d` and `hl`.

This doesn't seem desirable at all.

**Comment by aaaaaa123456789** [comment]
I'll point out that it can also lead to confusion. Many people would expect `ld a, [$ - 1]` to read the byte before the current address, as it would in many other assemblers... yet it would actually assemble into `ld a, [$ffff]`.

**Comment by AntonioND** [comment]
Interesting. I agree, this should be a syntax error.
