### ISSUE TITLE
Signed integer overflow

### ISSUE THREAD

**Issue by dbrotz** [rednex/rgbds#313]
If you assemble the following code with rgbasm compiled with `-fsanitize=signed-integer-overflow`, you get a runtime error indicating that signed overflow occurred.

```
x = 2147483647 + 1
```

Clang and GCC have non-standard builtin functions to safely handle integer operations that could overflow.
https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html
https://clang.llvm.org/docs/LanguageExtensions.html#checked-arithmetic-builtins

If we want to avoid relying on compiler-specific extensions, we could perform the operations with 64-bit integers, detect overflow, and convert to 32-bit.

**Comment by aaaaaa123456789** [comment]
Instead of relying on GCC and Clang for this, it's probably worthwhile to just detect _where_ the overflow is occurring and fix it properly. If this is not possible, `-fwrapv` is most likely the best solution.

**Comment by AntonioND** [comment]
The problem is that most overflows like this depend on text input, so it is pretty hard to detect where there are problems. And, even if you do detect them, how do you fix them? Do you actually implement the 2's complement behaviour in safe C? Or do you show an error and exit? Maybe ``-fwrapv`` is the best solution, yes. It is not a real fix from a strict point of view, but it makes the behaviour predictable.

**Comment by dbrotz** [comment]
`-fwrapv` is fine if you don't want to warn the user about the overflow.

**Comment by aaaaaa123456789** [comment]
Implementing two's complement behaviour in safe C is as simple as using unsigned types.

**Comment by AntonioND** [comment]
Well, yeah, but that means you need to start adding casts that look weird. Either you also add comments to explain why they are there or someone may think thet are useless. If what we want is to make sure that we always use two's complement, it makes sense to tell that to the compiler, I think.

**Comment by aaaaaa123456789** [comment]
Is there any particular reason to use signed types for user data (e.g., instruction operands)? Using unsigned types in general would solve the issue without the need for casts

**Comment by aaaaaa123456789** [comment]
@dbrotz That's not necessarily true. The sign of a product only matters for full products (i.e., multiplications where the result is twice as wide as its operands — for instance, a 64-bit result for 32-bit multiplication). If the result is as wide as the operands (which is the case here, where everything is 32 bits), signed and unsigned multiplication give the same result.

This is, however, not true for division.

**Comment by dbrotz** [comment]
Interesting. That still leaves division as a problem.

By the way, one thing I don't like about `-fwrapv` is that it would affect other code as well, since it can only be applied at a file granularity, as far as I know.

**Comment by aaaaaa123456789** [comment]
Division is undefined when the divisor is zero, obviously. Other than that, unsigned division can't overflow, but signed division has exactly one case of overflow, which is `MIN_INT / -1` — which is undefined.

So any handling of signed division has to deal with that special case. (I think `-fwrapv` takes care of that too by returning `MIN_INT` for the division and `0` for the remainder.)

And yes, `-fwrapv` is file-granular at best.
