### ISSUE TITLE
[Feature request] Full file path in error messages

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#314]
I am compiling a project with the `-i src/` flag passed to RGBASM. I have an error in file `src/engine/studio_screen.asm`, which is included from `src/engine.asm` as `INCLUDE "engine/studio_screen.asm"`.

RGBASM outputs the following line: `ERROR: src/engine.asm(6) -> engine/studio_screen.asm(20): (error description)`.
My request is for RGBASM to instead output `ERROR: src/engine.asm(6) -> src/engine/studio_screen.asm(20):`

Upsides:
- Removes ambiguity as to which file was compiled, useful if you have a large project and you somehow made two files under the same name
- Improves analysis from external tools (I just discussed with the maintainer of the VS Code extension)

Downsides:
- Breaks compatibility with any tools using the old syntax (although I'm not *that* sure any exist). Guess a flag could be used.

**Comment by AntonioND** [comment]
I don't think we should worry about compatibility in this case, to be honest...
