### ISSUE TITLE
rgbasm reports the wrong filename when a symbol is redefined

### ISSUE THREAD

**Issue by mid-kid** [rednex/rgbds#316]
Test case
---
`file1.asm`:
```
SECTION "a", ROM0
    dw sym
INCLUDE "test2.asm"
sym:
```
`file2.asm`:
```
sym:
```

Result
---
```
$ rgbasm test1.asm 
ERROR: test1.asm(4):
    'sym' already defined in test1.asm(2)
error: Assembly aborted in pass 1 (1 errors)!
```

This result is unexpected. The symbol was defined first in `test2.asm`, not `test1.asm`

**Comment by mid-kid** [comment]
This patch fixes the issue: https://pastebin.com/raw/JS05aJPC

**Comment by mid-kid** [comment]
Because I'm not sure if that is a proper way to fix it.

**Comment by AntonioND** [comment]
Well, fair enough, but it's easier to review code in a PR.
