### ISSUE TITLE
Double dereferencing EQUS symbols is impossible

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#320]
The problem is as follows:
I'm adding data defining to [rgbds-structs](https://github.com/ISSOtm/rgbds-structs), and for this I need to double-deref a symbol:

`STRUCT_FIELD_TYPE` equs "NPC_field0_type" (dynamically generated to iterate over struct fields)
`NPC_field0_type` equs "B" (contains the actual info, it's the second character of "DB", or "DW", or "DL")

I thus typed this:
```
DATA_TYPE equs "D{{STRUCT_FIELD_TYPE}}"
```
and got:
```
ERROR: src/home.asm(13) -> home/overworld.asm(1228) -> dstruct(35) -> dstruct(8):
    '{STRUCT_FIELD_TYPE' not defined
ERROR: src/home.asm(13) -> home/overworld.asm(1228) -> dstruct(35) -> dstruct(11) -> dstruct(1):
    syntax error
```

The workaround I currently have is this:
```
TMP equs STRCAT("\{", STRCAT("{STRUCT_FIELD_TYPE}", "\}")) ; Temp var for double deref because "{{STRUCT_FIELD_TYPE}}" is a syntax error
DATA_TYPE equs STRCAT("D", TMP)
PURGE TMP
```
...and even I don't like it.

**Comment by AntonioND** [comment]
To be fair, I think this was never the intended way to use that...

**Comment by ISSOtm** [comment]
I wouldn't call it an "enhancement", but instead a parser bug. I'd expect the grammar to match the outer braces correctly, then the inner braces. I would classify the inner braces expanding before the outer ones an enhancement, and even then I think it's stretching things a bit.

**Comment by AntonioND** [comment]
That's up to interpretation. I think that if this has never worked and the parser doesn't even support it, it means it wasn't the original intention. For example, you can nest macros because the parser was designed for it. In order to support nested braces you need to improve the parser, and that's more like an enhancement.
