### ISSUE TITLE
rgbgfx "the application was unable to start correctly" windows 10 64bit

### ISSUE THREAD

**Issue by gingemonster** [rednex/rgbds#324]
v0.3.8 downloaded today and tried to run rgbgfx.exe on windows and I get a windows error saying "the application was unable to start correctly"

**Comment by AntonioND** [comment]
32 or 64 bits?

**Comment by gingemonster** [comment]
64bit, the previous version works

**Comment by AntonioND** [comment]
Ok, for now you can use the previous version because there have been no changes to rgbgfx between both releases. I'll take a look at this.

**Comment by gingemonster** [comment]
thanks

**Comment by AntonioND** [comment]
So I think I put the wrong DLLs in the win32/64 zips. Can you try now?

**Comment by gingemonster** [comment]
thats working now thanks
