### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by rc-05** [rednex/rgbds#331]
I was trying to package rgbds (latest release version 0.3.8) for Void Linux and during the compilation step with make this happened:
```
src/asm/asmy.c:480:23: error: conflicting types for 'yylex'
 # define YYLEX_DECL() yylex(void)
                       ^~~~~
src/asm/asmy.c:485:5: note: in expansion of macro 'YYLEX_DECL'
 int YYLEX_DECL();
     ^~~~~~~~~~
In file included from include/asm/fstack.h:20,
                 from src/asm/asmy.y:21:
include/asm/lexer.h:66:10: note: previous declaration of 'yylex' was here
 uint32_t yylex(void);
          ^~~~~
```

Gonna list the dependencies used:
- pkg-config-0.29.2_2
- byacc-20180609_1
- flex-2.6.4_3
- libpng-devel-1.6.36_1

**Comment by AntonioND** [comment]
Now that https://github.com/rednex/rgbds/pull/336 has been merged, could you try again?

**Comment by rc-05** [comment]
I've tried again but still no luck: I even tried to use bison but to no avail.
It gives this same error when building the release 0.3.8:
```
src/asm/asmy.c:480:23: error: conflicting types for 'yylex'
 # define YYLEX_DECL() yylex(void)
                       ^~~~~
src/asm/asmy.c:485:5: note: in expansion of macro 'YYLEX_DECL'
 int YYLEX_DECL();
     ^~~~~~~~~~
In file included from include/asm/fstack.h:20,
                 from src/asm/asmy.y:21:
include/asm/lexer.h:66:10: note: previous declaration of 'yylex' was here
 uint32_t yylex(void);
          ^~~~~
make: *** [Makefile:121: src/asm/asmy.o] Error 1
```

**Comment by rc-05** [comment]
I've tried building with bison and surprisingly it worked (altrough with two warnings)
I don't know why it gives that problem only when using yacc

**Comment by AntonioND** [comment]
I don't think you're testing with the latest master, that line in lexer.h has changed since you reported the bug.

**Comment by AntonioND** [comment]
Have you tried with the latest master? If that works I'd like to close this issue.

**Comment by rc-05** [comment]
I have built the latest **release** distribution.
Maybe I will try to build the master branch instead

**Comment by AntonioND** [comment]
Then this issue can be closed.
