### ISSUE TITLE
Issues Making on Windows 7

### ISSUE THREAD

**Issue by ChefFloyardee** [rednex/rgbds#332]
Hi all.

I have Windows 7, and I use Cygwin to work on my Pokemon ROM hack.

I want to make custom sprites, so I need a way to convert png to 2bpp.

I thus tried to install and make rgbds to use the rgbgfx function.

I added the depencies via Cygwin, and in Cygwin I do

cd rgbds

then 

make.

But then this comes up.

src/asm/asmy.y: warning: 1 shift/reduce conflict [-Wconflicts-sr]src/asm/asmy.y: warning: 3 reduce/reduce conflicts [-Wconflicts-rr]

The files make, but I cannot open them.

Please help if you can :D

**Comment by AntonioND** [comment]
That warning is a know issue and it shouldn't affect you: https://github.com/rednex/rgbds/issues/44

Can you build the ROM without modifying anything?

**Comment by AntonioND** [comment]
@ChefFloyardee Any comments?

**Comment by ChefFloyardee** [comment]
I found a program that converts the files for me, so I would call this resolved.

**Comment by AntonioND** [comment]
Which program? If there is still a problem with rgbgfx it would be nice to know. I guess you tried with the prebuilt binaries? https://github.com/rednex/rgbds/releases/tag/v0.3.8

**Comment by ChefFloyardee** [comment]
It is called "SNES Converter".

I think the pre-built works as well though, so maybe I do not even need it.

**Comment by AntonioND** [comment]
Well, if you have an error message to show regarding the compilation of ``rgbgfx`` (try compiling with ``make Q=``) it would be useful to have it here. Most likely it's a problem related to missing ``libpng``. If not, it's better to close this issue.

**Comment by AntonioND** [comment]
If there is more information we can reopen this, but closing it for now.
