### ISSUE TITLE
rgbfix 16-char title omits last character

### ISSUE THREAD

**Issue by huderlem** [rednex/rgbds#344]
rgbfix has a bug where a 16-character title results in the last character being omitted.  The offending line of code is:
```
int n = snprintf((char *)header + 0x34, 16, "%s", title);
```

`snprintf()`' is not an appropriate function to use here because it appends a null-terminating character, however, a null-terminating character is not desired in the case of a 16-char title.

I'm working on a PR for this currently.

**Comment by AntonioND** [comment]
Fixed in https://github.com/rednex/rgbds/pull/345
