### ISSUE TITLE
duplicate entries in make dependency file generation

### ISSUE THREAD

**Issue by stoneface86** [rednex/rgbds#347]
When using the `-M dependfile` option in rgbasm, the resulting dependency file has duplicate entries. For example

foo.asm
```asm
INCLUDE "A.inc"
SECTION "code", ROM0
nop
```
A.inc
```asm
INCLUDE "B.inc"
```

B.inc (empty file)
```asm
```
Assemble:
```sh
rgbasm -M foo.d -o foo.obj foo.asm
```
foo.d:
```Makefile
foo.obj: foo.asm
foo.obj: A.inc
foo.obj: B.inc
foo.obj: A.inc
foo.obj: B.inc
```

The above file will also be generated if A.inc is empty and `INCLUDE "B.inc"` is added to foo,asm. The correct file should be the same as the above without the last two lines (kinda looks like it got written twice somehow).

While this file does list all dependencies for foo.obj and will work fine in make, it could be an issue for projects with a large number of includes.

**Comment by ISSOtm** [comment]
It has been a problem for me, causing recipe overrides in Make (which is undefined behavior, btw), and required piping the output through `sort | uniq`
I have ~600 such lines already, especially after being passed to a `sed` script to simulate `-MP`

**Comment by NieDzejkob** [comment]
Does this still happen on current master? The parser was rewritten
semi-recently to use only one pass.

**Comment by ISSOtm** [comment]
I haven't been able to find a duplicate entry using latest master.

**Comment by ISSOtm** [comment]
For that reason, closing unless the issue resurfaces.
