### ISSUE TITLE
Labels can be defined with colons in their name

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#362]
```
issotm@link-panda tmp.rLFWz9K2Ej% cat label.asm
labels: macro
\1
End\1
endm

SECTION "Test", ROM0
 labels Test:
issotm@link-panda tmp.rLFWz9K2Ej% rgbasm -E -o label.o label.asm          
issotm@link-panda tmp.rLFWz9K2Ej% rgblink -n label.sym -o label.gb label.o
issotm@link-panda tmp.rLFWz9K2Ej% cat label.sym
; File generated by rgblink

00:0000 Test
00:0000 EndTest:
issotm@link-panda tmp.rLFWz9K2Ej% 
```
I expected the second label to be defined like the first, without the colon.

**Comment by dbrotz** [comment]
It's worse than that. Any character that can be used in a macro arg can be used in a symbol name using this trick. For example, you can even put spaces in a symbol name. The following code produces a label with the name "xa b".

```
SECTION "sec", ROM0

m: MACRO
x\1
	global x\1
ENDM

	m a b
```

To fix this, we probably want to end the symbol token early and process the rest of the macro arg as separate tokens.
