### ISSUE TITLE
String equates may not be properly terminated

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#363]
Here's the minimal reproducer I came up with, though I've been unsuccessful at debugging it on my own.
```
issotm@sheik-kitty ~% rgbasm -V
rgbasm v0.3.8-33-gd00ec02
issotm@sheik-kitty tmp.Iw3QESWHAw% cat a.asm
FIELD_0_INITIALIZER equs "1"
FIELD_1_INITIALIZER equs "$7F"
FIELD_2_INITIALIZER equs "BANK(Label)"
FIELD_3_INITIALIZER equs "SOME_CONSTANT_WITH_A_LONG_NAME"

ID = 0
REPT 4
ID_STR equs STRSUB("{ID}", 2, STRLEN("{ID}") - 1)
GET_INITIALIZER_VALUE equs "INITIALIZER_VALUE equs \{FIELD_{ID_STR}_INITIALIZER\}"
	PURGE ID_STR
GET_INITIALIZER_VALUE
	PURGE GET_INITIALIZER_VALUE
	PRINTT "{INITIALIZER_VALUE}\n"
	PURGE INITIALIZER_VALUE
ID = ID + 1
ENDR
issotm@sheik-kitty tmp.Iw3QESWHAw% rgbasm a.asm
1
$7F
BANK(Label)_VALUE
SOME_CONSTANT_WITH_A_LONG_NAME3_INITIALIZER}
issotm@sheik-kitty tmp.Iw3QESWHAw% 
```

**Comment by dbrotz** [comment]
It turns that when you have a standalone bracketed symbol, it doesn't terminate the string.
`X EQUS {Y}`
You can use this as a workaround until my fix get merged.
`X EQUS "{Y}"`

**Comment by dbrotz** [comment]
It turns out that when you have a standalone bracketed symbol, it doesn't terminate the string.
`X EQUS {Y}`

You can use this as a workaround until my fix get merged.
`X EQUS "{Y}"`

**Comment by ISSOtm** [comment]
This is a correct workaround, but for some reason RGBASM still softlocks when assembling my file; if unrelated I will investigate separately, though I lack info about that one at least for now.
