### ISSUE TITLE
`PUSHS` outside of a section crashes the assembler

### ISSUE THREAD

**Issue by mid-kid** [rednex/rgbds#373]
This snippet of code, when used in an otherwise empty file:
```
PUSHS
POPS
```
Seems to cause a segmentation fault. This is probably because the assembler expects `PUSHS` to be used inside of a valid section.

This fault was discovered by @ISSOtm on the gbdev discord.

**Comment by pinobatch** [comment]
I reproduced this problem using RGBDS v0.3.8-57-gb019b03 with GCC 7.4.0 on Ubuntu 18.04.

**Comment by Ben10do** [comment]
I'll have a proper look at this later, but it seems like it'd be straightforward to add an extra check to `out_PushSection()` for this edge case. Do you have any indication of where the segfault happens? (Glancing at the code, there don't seem to be any *really* obvious culprits)

**Comment by ISSOtm** [comment]
The failure occurs in out_PopSection with out_SetCurrentSection being
called with a NULL pointer.

**Comment by Ben10do** [comment]
Ah, I missed the dereference in `out_SetCurrentSection()` to restore whatever the PC was. Anyway, PR now opened.

**Comment by ISSOtm** [comment]
Is this really the correct behavior? I have a macro that does a PUSHS that is called from a "section-less" context, and I simply expect `PUSHS` to push that lack of context.

**Comment by Ben10do** [comment]
Good question; maybe I was a little hasty in my interpretation of this issue. I didn't think earlier of a use-case for pushing/popping a section-less context, but thinking about it, it might be useful for `INCLUDE`d files to add their own sections even if the outer file hasn't defined any sections yet. I'll see how feasible it'd be to do this.

**Comment by Ben10do** [comment]
PR updated. Hopefully this is now more what you were intending, @ISSOtm! 🙂
