### ISSUE TITLE
`make checkpatch` doesn't cover `src/asm/asmy.y`

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#391]
Happened during the making of #390, where I realized I didn't follow the coding style properly in that file, but that didn't bother `make checkpatch`.

**Comment by AntonioND** [comment]
I'm not sure if this can be done. The syntax of ``.y`` files is different than ``.c`` files, so ``checkpatch.pl`` wouldn't work. Also, checking ``asmy.c`` wouldn't be a great idea because it's auto-generated.

**Comment by ISSOtm** [comment]
Figured as much, except some parts of the yacc file are straight up C. Couldn't those be parsed, at the very least?

**Comment by AntonioND** [comment]
Sure, you could create a script that extracts the C parts of that file, but I'm not sure if it's worth the effort. Most of the file isn't in C.

**Comment by ISSOtm** [comment]
Okay then.
