### ISSUE TITLE
Does `test/asm/line-cont.asm` test what it says on the tin?

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#393]
The error with that file is `Macro '@' not defined`, but that doesn't match the name of the file (rather, `macro-@` tests for the same thing).

What is it intended to test?

**Comment by dbrotz** [comment]
It was added to test the fix for #302. That code used to crash rgbasm because it would eat the newline at the end of the file.

**Comment by ISSOtm** [comment]
But then shouldn't the error be different?

**Comment by dbrotz** [comment]
Putting `\` at the end of the file shouldn't cause an error. It's just that that particular code, which should have caused `Macro '@' not defined` error, used to crash the assembler, so the test was added to prevent regressions.

**Comment by ISSOtm** [comment]
I see; what I'm concerned with is that I find *what* the test is doing fairly obscure. I'd expect the test to simply succeed, for example.

```
PRINTT \
```
for example fails with a syntax error on line 2, which makes it more clear what the expected behavior is.

I'm also not too keen on relying on a separate error to trigger, in case the behavior changes.

**Comment by dbrotz** [comment]
I see what you're saying, but that particular code wouldn't have tested the fix. The lexer needs to be in a macro arg processing context. I can submit a PR to update this.

**Comment by ISSOtm** [comment]
Hm, I see. Maybe a comment explaining what's being tested would be a good idea, yes.
