### ISSUE TITLE
Cannot construct some valid symbols using macros

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#396]
The faulty line is this one:
https://github.com/ISSOtm/rgbds-structs/blob/39b4cd67fd0a1c843d011c41cecd09ece23561a9/structs.asm#L306

The error produced leads me to believe that the line is interpreted as a macro instead of as a label. I'm not sure why.

`git bisect` said:
> c75a9539bac624b5e524c74ffa37a065f532585a is the first bad commit

**Comment by ISSOtm** [comment]
Ok, found the problem.

https://github.com/ISSOtm/rgbds-structs/blob/39b4cd67fd0a1c843d011c41cecd09ece23561a9/structs.asm#L357

When called with the second argument being `.player`, this yields symbol `sizeof_.player`. c75a953 restored what I'm assuming is correct behavior, but the error message should be made different, I believe.

What's weird is that the following program compiles and prints `$0`:
```
sizeof_.something equ 0
```

**Comment by dbrotz** [comment]
Using a '.' in a symbol name should have been allowed. Sorry about that. I've submitted a PR to fix it.

**Comment by ISSOtm** [comment]
Coincidentally, I have just proposed #399, which features a different test than your #398. Which one do you think is better?

**Comment by dbrotz** [comment]
I think it's good that you're testing more special characters. I did like how I used a new "print" macro to shorten some of the test cases. You can add that if you think it's a good idea. I'll close my PR.

**Comment by ISSOtm** [comment]
I used `printt` with a bracket expansion. I think that should work the same?

**Comment by dbrotz** [comment]
I meant that I shortened the existing test cases that were using `printv` followed by `printt`.

**Comment by ISSOtm** [comment]
Oh, I'll do that, then.

**Comment by ISSOtm** [comment]
Done, once CI completes I will merge the PR.

**Comment by dbrotz** [comment]
Thanks.

**Comment by ISSOtm** [comment]
Closed via #399.
