### ISSUE TITLE
test/asm/undefined-dot.asm fails when no output file is provided

### ISSUE THREAD

**Issue by NieDzejkob** [rednex/rgbds#404]
This breaks `update-refs.sh`

**Comment by ISSOtm** [comment]
Rather than change the test, it'd be better to figure out what's different when no output file is defined.

Expected behavior is that `rgbasm input.asm` acts as `rgbasm -o /dev/null input.asm`, right?

**Comment by ISSOtm** [comment]
Looks like some errors, such as this one, are performed in `out_WriteObject`, but that function is skipped entirely when `-o` isn't specified.
