### ISSUE TITLE
[Feature request] Proper support for warnings

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#414]
Some things raise warnings in the assembler or the linker. There are also some errors that should be warnings (e.g., #279), some things that don't raise any warning at all because the warning would be of very limited use (e.g., #202), and some warnings that could be added (there's a lot of room for creativity here).

But none of this is very useful without better support for warnings.

By "better" I mean the kind of support you find in compilers, with switches to enable/disable warnings of various kinds, turn some warnings into errors, and so on.

I understand that this would require using long options in the command line — this is hardly a drawback.

**Comment by bentley** [comment]
Why would that require long options?

**Comment by aaaaaa123456789** [comment]
Because there are multiple kinds of warnings the user would want to enable or disable.

**Comment by aaaaaa123456789** [comment]
I suppose warning flags could become arguments (e.g., `-w all`), avoiding the need for long options.

**Comment by bentley** [comment]
Yes, exactly.

POSIX getopt treats `-xfoo` the same as `-x foo`, if x is defined as taking an argument.
