### ISSUE TITLE
STRCAT and MACROS

### ISSUE THREAD

**Issue by RadAd** [rednex/rgbds#415]
I found in the documentation regarding using STRCAT with MACRO like this:

M1:  MACRO
        PRINTT \1
        ENDM

        M1 STRCAT(\"Hello\"\, \"Foo\")

I kind of understand why the escaping is necessary but it would be better if it wasn't needed. What I am struggling with though is a second level macro:

M2:  MACRO
        M1 STRCAT(\1, \"ABC\")
        ENDM

        M2 "Hello"

And what escaping is needed here if possible?

**Comment by dbrotz** [comment]
You need to escape the comma so that it's not treated as an argument separator.

```
M1: MACRO
PRINTT \1
ENDM

M2: MACRO
	M1 STRCAT(\1\, "ABC")
ENDM

	M2 "Hello"
```

**Comment by ISSOtm** [comment]
That said, normally `M1 STRCAT("Hello"\, "World")` should work, shouldn't it?

**Comment by dbrotz** [comment]
Yes. I don't think that escaping quotes in macro arguments makes a difference.

**Comment by RadAd** [comment]
Yeah that works.
Thanks.

**Comment by ISSOtm** [comment]
That said, if the docs state that quotes need to be escaped in macro args, they should be corrected.

**Comment by AntonioND** [comment]
I'm not sure if this is needed or not, but the code is prepared for it: https://github.com/rednex/rgbds/blob/65fc42cce50de0a5039e703f6be568a29e23e213/src/asm/lexer.c#L901-L927
