### ISSUE TITLE
Inconsistent use of error functions

### ISSUE THREAD

**Issue by stag019** [rednex/rgbds#42]
Just leaving my notes here, I don't care if you fix it or wait for me to get around to it, but I'd like to free up some text files from my computer and this seems like the place to put it.

This was just me `grep`ing "err" in all the files, so excuse the mistake if there's something in here that shouldn't be deleted.

include/asm/main.h:void fatalerror(const char *fmt, ...);
include/asm/main.h:void yyerror(const char *fmt, ...);
include/asm/main.h:#define  YY_FATAL_ERROR fatalerror
src/link/main.c:                fprintf(stderr, "Argument for option 'p' must be between 0 and 0xFF");
src/asm/gameboy/yaccprt4.y:             yyerror("Address $%x not 16-bit", $6);
src/asm/gameboy/yaccprt4.y:                 yyerror("ROM bank value $%x out of range (1 to $1ff)", $8);
src/asm/gameboy/yaccprt4.y:                 yyerror("SRAM bank value $%x out of range (0 to 3)", $8);
src/asm/gameboy/yaccprt4.y:                 yyerror("WRAMX bank value $%x out of range (1 to 7)", $8);
src/asm/gameboy/yaccprt4.y:                 yyerror("VRAM bank value $%x out of range (0 to 1)", $8);
src/asm/gameboy/yaccprt4.y:             yyerror("BANK only allowed for ROMX, WRAMX, SRAM, or VRAM sections");
src/asm/gameboy/yaccprt4.y:                     yyerror("ROM bank value $%x out of range (1 to $1ff)", $11);
src/asm/gameboy/yaccprt4.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/gameboy/yaccprt4.y:                     yyerror("SRAM bank value $%x out of range (0 to 3)", $11);
src/asm/gameboy/yaccprt4.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/gameboy/yaccprt4.y:                     yyerror("WRAMX bank value $%x out of range (1 to 7)", $11);
src/asm/gameboy/yaccprt4.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/gameboy/yaccprt4.y:                     yyerror("VRAM bank value $%x out of range (0 to 1)", $11);
src/asm/gameboy/yaccprt4.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/gameboy/yaccprt4.y:             yyerror("BANK only allowed for ROMX, WRAMX, SRAM, or VRAM sections");
src/asm/gameboy/yaccprt4.y:                         yyerror("Source address $%x not in HRAM ($FF00 to $FFFE)", $4.nVal);
src/asm/gameboy/yaccprt4.y:                         yyerror("Destination address $%x not in HRAM ($FF00 to $FFFE)", $2.nVal);
src/asm/gameboy/yaccprt4.y:                         yyerror("LD [HL],[HL] not a valid instruction");
src/asm/gameboy/yaccprt4.y:                         yyerror("Destination operand must be A");
src/asm/gameboy/yaccprt4.y:                         yyerror("Destination operand must be A");
src/asm/gameboy/yaccprt4.y:                         yyerror("Destination operand must be A");
src/asm/gameboy/yaccprt4.y:                         yyerror("Address for RST must be absolute");
src/asm/gameboy/yaccprt4.y:                         yyerror("Invalid address $%x for RST", $2.nVal);
src/asm/rpn.c:          yyerror("'%s' not defined", tzSym);
src/asm/rpn.c:      yyerror("BANK argument must be a relocatable identifier");
src/asm/fstack.c:       fatalerror("No memory for context");
src/asm/fstack.c: \* Dump the context stack to stderr
src/asm/fstack.c:       fprintf(stderr, "%s(%ld) -> ", pLastFile->tzFileName,
src/asm/fstack.c:   fprintf(stderr, "%s(%ld)", tzCurrentFileName, nLineNo);
src/asm/fstack.c:       fatalerror("No such macroargument");
src/asm/fstack.c:       yyerror("No such string symbol '%s'", s);
src/asm/yaccprt1.y:             fatalerror("Symbol value too long to fit buffer");
src/asm/yaccprt1.y:         fatalerror("snprintf encoding error");
src/asm/yaccprt1.y:             fatalerror("Symbol value too long to fit buffer");
src/asm/yaccprt1.y:     fatalerror( "No mem for REPT block" );
src/asm/yaccprt1.y:     fatalerror( "No mem for MACRO definition" );
src/asm/asmy.y:             fatalerror("Symbol value too long to fit buffer");
src/asm/asmy.y:         fatalerror("snprintf encoding error");
src/asm/asmy.y:             fatalerror("Symbol value too long to fit buffer");
src/asm/asmy.y:     fatalerror( "No mem for REPT block" );
src/asm/asmy.y:     fatalerror( "No mem for MACRO definition" );
src/asm/asmy.y:                         yyerror("Macro '%s' not defined", $1);
src/asm/asmy.y:                 { fatalerror("%s", $2); }
src/asm/asmy.y:                 { yyerror("%s", $2); }
src/asm/asmy.y:                         yyerror("Immediate value must be 3-bit");
src/asm/asmy.y:                         yyerror("Expression must be PC-relative");
src/asm/asmy.y:                         yyerror("Expression must be 8-bit");
src/asm/asmy.y:                         yyerror("Expression must be 16-bit");
src/asm/asmy.y:             yyerror("Address $%x not 16-bit", $6);
src/asm/asmy.y:                 yyerror("ROM bank value $%x out of range (1 to $1ff)", $8);
src/asm/asmy.y:                 yyerror("SRAM bank value $%x out of range (0 to 3)", $8);
src/asm/asmy.y:                 yyerror("WRAMX bank value $%x out of range (1 to 7)", $8);
src/asm/asmy.y:                 yyerror("VRAM bank value $%x out of range (0 to 1)", $8);
src/asm/asmy.y:             yyerror("BANK only allowed for ROMX, WRAMX, SRAM, or VRAM sections");
src/asm/asmy.y:                     yyerror("ROM bank value $%x out of range (1 to $1ff)", $11);
src/asm/asmy.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/asmy.y:                     yyerror("SRAM bank value $%x out of range (0 to 3)", $11);
src/asm/asmy.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/asmy.y:                     yyerror("WRAMX bank value $%x out of range (1 to 7)", $11);
src/asm/asmy.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/asmy.y:                     yyerror("VRAM bank value $%x out of range (0 to 1)", $11);
src/asm/asmy.y:                 yyerror("Address $%x not 16-bit", $6);
src/asm/asmy.y:             yyerror("BANK only allowed for ROMX, WRAMX, SRAM, or VRAM sections");
src/asm/asmy.y:                         yyerror("Source address $%x not in HRAM ($FF00 to $FFFE)", $4.nVal);
src/asm/asmy.y:                         yyerror("Destination address $%x not in HRAM ($FF00 to $FFFE)", $2.nVal);
src/asm/asmy.y:                         yyerror("LD [HL],[HL] not a valid instruction");
src/asm/asmy.y:                         yyerror("Destination operand must be A");
src/asm/asmy.y:                         yyerror("Destination operand must be A");
src/asm/asmy.y:                         yyerror("Destination operand must be A");
src/asm/asmy.y:                         yyerror("Address for RST must be absolute");
src/asm/asmy.y:                         yyerror("Invalid address $%x for RST", $2.nVal);
src/asm/globlex.c:              fatalerror("Malformed ID");
src/asm/globlex.c:      fatalerror("Symbol too long");
src/asm/globlex.c:          yyerror("Macro argument not defined");
src/asm/globlex.c:      yyerror("Invalid macro argument");
src/asm/globlex.c:      yyerror("Macro unique label string not defined");
src/asm/output.c:       fatalerror("No memory for section stack");
src/asm/output.c:       fatalerror("No entries in the section stack");
src/asm/output.c:   fatalerror("INTERNAL: Unknown section");
src/asm/output.c:       fatalerror("No memory for patchsymbol");
src/asm/output.c:       fatalerror("No memory for patch");
src/asm/output.c:       fatalerror("Code generation before SECTION directive");
src/asm/output.c:               fatalerror
src/asm/output.c:               fatalerror
src/asm/output.c:               fatalerror("Not enough memory for section");
src/asm/output.c:           fatalerror("Not enough memory for sectionname");
src/asm/output.c:       fatalerror("Not enough memory for section");
src/asm/output.c:       yyerror("PC-relative value must be 8-bit");
src/asm/output.c:       fatalerror("Start position cannot be negative");
src/asm/output.c:       fatalerror("Number of bytes to read must be greater than zero");
src/asm/output.c:       fatalerror("Specified start position is greater than length of file");
src/asm/output.c:       fatalerror("Specified range in INCBIN is out of bounds");
src/asm/main.c:     fatalerror("Unknown option");
src/asm/main.c:     fatalerror("No memory for option stack");
src/asm/main.c:     fatalerror("No entries in the option stack");
src/asm/main.c:verror(const char *fmt, va_list args)
src/asm/main.c: fprintf(stderr, "ERROR:\t");
src/asm/main.c: fprintf(stderr, " :\n\t");
src/asm/main.c: vfprintf(stderr, fmt, args);
src/asm/main.c: fprintf(stderr, "\n");
src/asm/main.c:yyerror(const char *fmt, ...)
src/asm/main.c: verror(fmt, args);
src/asm/main.c:fatalerror(const char *fmt, ...)
src/asm/main.c: verror(fmt, args);
src/asm/symbol.c:       fatalerror("No memory for symbol");
src/asm/symbol.c:       yyerror("'%s' not defined", tzName);
src/asm/symbol.c:           fatalerror("'%s' is not allowed as argument to the "
src/asm/symbol.c:       yyerror("Stringsymbol '%s' not defined", tzSym);
src/asm/symbol.c:           fatalerror("Expression must have a constant value");
src/asm/symbol.c:       yyerror("'%s' not defined", s);
src/asm/symbol.c:               yyerror("'%s' is a macro or string symbol", s);
src/asm/symbol.c:           yyerror("'%s' not defined", s);
src/asm/symbol.c:               yyerror("'%s' is a macro or string symbol", s);
src/asm/symbol.c:           yyerror("'%s' not defined", s);
src/asm/symbol.c:       yyerror("'%s' not defined", s);
src/asm/symbol.c:       yyerror("A maximum of 9 arguments allowed");
src/asm/symbol.c:               yyerror("'%s' already defined", tzSym);
src/asm/symbol.c:           yyerror("'%s' already defined", tzSym);
src/asm/symbol.c:           fatalerror("No memory for stringequate");
src/asm/symbol.c:                   yyerror("'%s' already defined", tzSym);
src/asm/symbol.c:           fatalerror("Local label in main scope");
src/asm/symbol.c:               yyerror("'%s' already defined", tzSym);
src/asm/symbol.c:       yyerror("'%s' not defined", tzSym);
src/asm/symbol.c:           yyerror("'%s' already defined", tzSym);
src/asm/symbol.c:               yyerror("'%s' already defined", tzSym);
src/asm/lexer.c:        fatalerror("Buffer safety margin exceeded");
src/asm/lexer.c:        fatalerror("Buffer safety margin exceeded");
src/asm/lexer.c:    fatalerror("Out of memory!");
src/asm/lexer.c:    fatalerror("Out of memory!");
src/asm/lexer.c:        fatalerror("Internal error in lexgetfloat");
src/asm/lexer.c:                fatalerror("Out of memory!");
src/asm/lexer.c:            fatalerror("Out of memory!");
src/asm/lexer.c:        fatalerror("Macro argument not defined");
src/asm/lexer.c:            fatalerror("Macro argument too long to fit buffer");
src/asm/lexer.c:        fatalerror("String too long");
src/asm/lexer.c:        fatalerror("Symbol too long");
src/asm/lexer.c:                fatalerror("Illegal character escape '%c'", ch);
src/asm/lexer.c:        yyerror("Missing }");
src/asm/lexer.c:                    fatalerror("Illegal character escape '%c'", ch);
src/asm/lexer.c:        yyerror("Unterminated string");
src/asm/lexer.c:                    fatalerror("Illegal character escape '%c'", ch);
src/asm/lexer.c:    fatalerror("Internal error in yylex_MACROARGS");
src/asm/lexer.c:    fatalerror("Internal error in yylex");
src/asm/yaccprt3.y:                         yyerror("Macro '%s' not defined", $1);
src/asm/yaccprt3.y:                 { fatalerror("%s", $2); }
src/asm/yaccprt3.y:                 { yyerror("%s", $2); }
src/asm/yaccprt3.y:                         yyerror("Immediate value must be 3-bit");
src/asm/yaccprt3.y:                         yyerror("Expression must be PC-relative");
src/asm/yaccprt3.y:                         yyerror("Expression must be 8-bit");
src/asm/yaccprt3.y:                         yyerror("Expression must be 16-bit");

**Comment by AntonioND** [comment]
As far as I see, there are two different types of error messages. Some of them inform about the assembler entering an invalid state or about broken code that affects the following code (unterminated macros or rept loops, for example). Others just inform about problems that prevent the assembler from generating valid code but don't affect the rest of the code. The first ones have to use faltalerror() because it isn't safe to continue. The rest have to use yyerror() to try to generate a comprehensive list of errors so that the coder can try to fix all of them at once instead of going one by one.
