### ISSUE TITLE
New webhook for GBDev Discord

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#429]
The GBDev Discord currently has a webhook for updates on [awesome-gbdev](/gbdev/awesome-gbdev), and has expressed interest in a similar setup for updates on RGBDS.

What do you think?

**Comment by NieDzejkob** [comment]
Personally, I like the idea. This is quite likely to be a result of me
being a member of the Discord server, though I don't think this should
be considered unusual -- after all, anyone not in the server could be
indiffrent at best.

**Comment by aaaaaa123456789** [comment]
This is harmless for non-members and beneficial for members, so I don't see any downsides. I personally asked for this a while ago.

**Comment by ISSOtm** [comment]
I'd prefer to have approval from another rednex member before doing anything.

**Comment by Ben10do** [comment]
I don't see any problem with doing this, so feel free!

**Comment by AntonioND** [comment]
Yeah, sure.

**Comment by ISSOtm** [comment]
The hook has been set up!
