### ISSUE TITLE
Shifts trigger undefined behavior

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#431]
Reference for all statements below: https://en.cppreference.com/w/c/language/operator_arithmetic#Shift_operators

## The problem

RGBDS transparently uses C's `<<` and `>>` operators; however, these operators have plenty of undefined cases, which should be handled consistently.

The rationale behind C's undefined behavior is ensuring fast processing independently from the platform; however, we want RGBDS-produced code to be consistent across platforms, especially since [the](https://github.com/pret/pokered) [disassemblies](https://github.com/pret/pokeyellow) [are](https://github.com/pret/pokecrystal) [a](https://github.com/pret/poketcg) [thing](https://github.com/pret/pokepinball). Therefore, we should use custom operators that do not exhibit such undefined behavior.

### Large shift amounts

> In any case, the behavior is undefined if `rhs` is negative or is greater or equal the number of bits in the promoted `lhs`. 

**Trigger cases:** RGBDS uses `int32_t` as its main "value" type, so unless compiled on a platform with 64-bit or larger `int`, shift amounts greater **or equal to** 32 are UB. Negative amounts obviously are as well.

**Current behavior:** If an expression is evaluated by RGBASM, it causes a fatal error:
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/asm/constexpr.c#L177-L182
But the linker doesn't care:
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/link/patch.c#L185-L192

**Proposed fixes:**
- Shift amounts larger than 32 should be clamped to 32
- Shifts by 32 should act as a shift by 31 followed by a shift by 1 to keep with user expectations
- What about negative shifts? @pinobatch voiced that they would expect this to flip the shift direction, but if that's not the current behavior we might break code that relies on it

### Right shifts of negative value

> For negative `LHS`, the value of `LHS >> RHS` is implementation-defined [...]

[GCC's behavior](https://gcc.gnu.org/onlinedocs/gcc/Integers-implementation.html#Integers-implementation):
> Signed ‘>>’ acts on negative numbers by sign extension.

I'm unable to find Clang's documentation of their implementation, however.

**Trigger cases:** Go figure, since there are no warnings. Probably some macros that shift bitfields?

**Current behavior:** Ignored, thus left to the compiler's implementation.

**Proposed fix:** Keep sign extension, but make it explicit for portability & future-proofing.

### Left shifts of negative value

I haven't found anything in the linked document about left shifts of negative values, only positive.

**Trigger cases:** [This](https://travis-ci.org/rednex/rgbds/jobs/582889877#L5376) and more.

**Current behavior:** Not sure, beyond a warning.
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/asm/constexpr.c#L173-L175

**Proposed fix:**
- Either keep current behavior, if it's critical, or
- Use bitwise shifting, since arithmetic shifting can be achieved through multiplication by a power of 2

**Comment by aaaaaa123456789** [comment]
Since RGBDS is not a C compiler, it can implement any semantics it wishes. I'd propose the following semantics, since they are more likely to meet users' expectations:

* `>>` should be an arithmetic shift, i.e., sign-extending. A new operator can be introduced for logical shifting (which I'd strongly recommend); `>>>` is a popular choice.
* Shifts by exactly 32 should work as expected and produce no warnings. (In other words, logical shifts in either direction result in 0 and arithmetic right shifts are equivalent to shifting by 31.)
* Shifts by more than 32 should behave like shifts by 32 and produce a warning.
* Negative shifts should behave like shifts in the opposite direction and always produce a warning. If the shift count is less than -32, it should be the same warning as for the previous point (i.e., shift count out of range); otherwise, a different warning should be shown, indicating that the shift count is negative.

Of course, these two last warnings could be supressed by the user if #414 is ever implemented.

**Comment by ISSOtm** [comment]
> If the shift count is less than -32, it should be the same warning as for the previous point (i.e., shift count out of range); otherwise, a different warning should be shown, indicating that the shift count is negative.
I'd rather output both warnings, both because the user *is* triggering two warn-able behaviors at once, and because it'd simplify implementation.

**Comment by aaaaaa123456789** [comment]
Seems reasonable to me.

**Comment by pinobatch** [comment]
The proposal to depart from C's definition of UB and define these behaviors looks good to me.

Large shift amounts
-------------------

The proposal looks good.

In general, I expect shift by an exponent `e > 1` to follow these [inductive](https://en.wikipedia.org/wiki/Mathematical_induction) identities:

    a << e == (a << 1) << (e - 1)
    a >> e == (a >> 1) >> (e - 1)

The proposal to clamp shift amounts at 32 and treat `>> 32` as `>> 31 >> 1` would preserve this. I wouldn't object to a warning for `e > 32`.

Right shifts of negative value
------------------------------

The proposal looks good.

I expect a shift to work like division by a power of two followed by a floor function. The Python language, for comparison, respects the following identity for integers `a` and exponents `e >= 0`:

    a >> e == a // (1 << e)

Arithmetic (sign-extending) shifts preserve this identity, producing `-5 >> 1 == -3` and `-4 >> 1 == -2`.  Thus this proposal would match the defined behavior of Java and Python.

Left shifts of negative value
-----------------------------

"Use bitwise shifting" looks good.

The mathematical identity in this case is as follows:

    a << e == a * (1 << e)

This identity matches bitwise shifting whenever this multiplication does not overflow. In a language with no unsigned types and overflowing operations on signed types, such as Java, users handling bitwise values by shifting and ANDing expect overflow to wrap.

**Comment by ISSOtm** [comment]
Looking at [GCC's docs on implementation-defined behavior](https://gcc.gnu.org/onlinedocs/gcc/Integers-implementation.html#Integers-implementation) it appears that the current behavior should be consistent with what's intended. I still haven't been able to find Clang's documentation on ID. MSVC [appears to](https://docs.microsoft.com/en-us/cpp/c-language/signed-bitwise-operations?view=vs-2019) [be consistent](https://docs.microsoft.com/en-us/cpp/c-language/right-shifts?view=vs-2019) with GCC, although their docs are less clear.

---

> Signed ‘>>’ acts on negative numbers by sign extension.

This implies that right shifting on signed types is fully defined and does an arithmetic shift. The annoying part here is that it's a GCC-specific behavior, *probably* also implemented by Clang, but there's no guarantee. Compiler-agnostic solutions are:
- Using `-fwrapv`, but it can affect more of the codebase (the practical impact *should* be however minimal) and isn't *exactly* compiler-agnostic
- Implementing this ourselves using division (poses a problem in regards to rounding)
- Implementing this ourselves using unsigned shifts + manual sign extension

---

> As an extension to the C language, GCC does not use the latitude given in C99 and C11 only to treat certain aspects of signed ‘<<’ as undefined.

This implies that this isn't UB like the standard says, but actually defined. The **types** provide two's complement, so it'd work as one expects. If we don't want to rely on GCC there, we can simply cast to the respective unsigned type, shift, and back again. Two's complement ensures things should go OK.

---

Too large shift amounts are not covered by this, but as noted above anything larger than 32 can be clamped to that, and then:
- Left shifts by 32 yield 0, nothing to see here
- Right shifts by 32 yield only sign bits, just like shifts by 31, which are correctly defined
- Right logical shifts also yield 0

(Assuming `sizeof(int) * CHAR_BIT` == 32, to simplify, but the actual code would use that expression.)

**Comment by aaaaaa123456789** [comment]
> If we don't want to rely on GCC there, we can simply cast to the respective unsigned type, shift, and back again. Two's complement ensures things should go OK.

Actually, casting back is implementation-defined. But indeed any relevant compiler defines it to work the way we'd want it to.

**Comment by ISSOtm** [comment]
Casting back shouldn't be ID, as both types implement two's complement semantics and are of the same size, right?

**Comment by aaaaaa123456789** [comment]
Signed types don't necessarily implement two's complement semantics, which is why the cast back is implementation-defined.

**Comment by ISSOtm** [comment]
[`intX_t` do](https://en.cppreference.com/w/c/types/integer), however

> signed integer type with width of exactly 8, 16, 32 and 64 bits respectively with no padding bits and using 2's complement for negative values (provided only if the implementation directly supports the type)
