### ISSUE TITLE
[Feature request] Flag to disable nop insertion after stop

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#433]
This is virtually identical to rgbasm's `-h` for `halt`, and for the same reasons. With the flag enabled, `stop` would emit just a `$10` byte.

**Comment by ISSOtm** [comment]
Isn't the byte after STOP always ignored? What would be the point of removing that extra byte?

**Comment by aaaaaa123456789** [comment]
If it is _always_ ignored, it can be used for data. I'm not sure if it is. 
That being said, writing a test ROM to check that is yet another case where you wouldn't want automatic NOP insertion.

**Comment by AntonioND** [comment]
Are you sure that it is safe to do? I'd be worried to do that if the documentation explicitly says you need to add a ``$00``.

**Comment by ISSOtm** [comment]
The documentation may actually be wrong about that, it seems like the byte is skipped entirely. But documentation about it is fairly unclear...

**Comment by pinobatch** [comment]
Another option: `stop $00` through `stop $FF` to specify the value of the skipped byte.

**Comment by aaaaaa123456789** [comment]
That seems like artificially inflating the opcode, since the `$10` is all that gets executed.

**Comment by pinobatch** [comment]
I see it as paralleling `brk` on 6502: the CPU executes the `brk` but then skips the next byte.
