### ISSUE TITLE
Future directions for RGBDS

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#435]
Concern has been expressed towards RGBDS updates mixing breaking changes and important bugfixes. We are complying with semantic versioning, since 0.x is basically "anything goes", but in practice we have users strongly relying on our API (the three repos used as part of the test suite probably are good enough examples), so we effectively are in 1.x

Part of the problem is that even small bugfixes can be breaking. Fixing #362 caused the following to stop working (and the behavior was clearly wrong, and it fixed some other code):
```
list_item: MACRO
.__item\1
if (_NARG > 1)
    db .__item\2 - .__item\1
endc
ENDM

current_list_item = 0

next_list_item: MACRO
next_list_item_index = current_list_item + 1
    list_item {current_list_item}, {next_list_item_index}
current_list_item = next_list_item_index
ENDM
```

Possible solutions:
- Bump version to 1.0.0 and start being careful with breaking changes
- Create a "LTS" branch that won't get minor changes and bugfixes that have *potential* to break backwards compatibility
- Do some pre-releases in addition to stable ones?

**Comment by mid-kid** [comment]
Why not just keep it like we're doing now except every minor version (note: not a _patch_ version) may break the API in some manner?
Develop a "stable" branch next to the development branch for the next 0.x.0.
As for when to switch to 1.0, I don't really know, but 0.x vs 1.x means very little for this project. Could even just drop the major version.

**Comment by Hawkbat** [comment]
Considering how certain large projects use RGBDS in the wild, I definitely think a 1.0.0 release makes sense. Breaking changes will be coming one way or another, so distinguishing non-breaking features from non-breaking bugfixes seems like it'll be useful for those maintainers.

**Comment by ISSOtm** [comment]
@pinobatch suggested releasing the rewritten RGBLINK (#434) as an alternative linker in RGBDS 0.3.9. I'd be down for doing that, then axing it for 1.0.0 after it gets sufficient testing from 0.3.9.
The motivation for people to use the new RGBLINK would be better error messages, and maybe more.

**Comment by mid-kid** [comment]
Is that really desireable? Aren't both versions supposed to be compatible? If so, why would a user notice the difference?

**Comment by ISSOtm** [comment]
They're *supposed* to be compatible, but given the amount of edge cases that have to be taken into account, I'm expecting bugs.

**Comment by pinobatch** [comment]
As precedent for side-by-side distribution of the stable and experimental linkers, I'd draw an analogy to a distribution that ships both the default linker of GNU Binutils and the rewritten ["gold" linker](https://en.wikipedia.org/wiki/Gold_(linker)). Or 2014 when Wikipedia was running a [beta test of HHVM](https://www.mediawiki.org/wiki/HHVM) (which was then a faster PHP interpreter) for users that opted in.

**Comment by mid-kid** [comment]
That's because gold and ld have a different featureset. These are two identical linkers with the exact same featureset.
It should never be expected for a new x.x.0 version to be completely flawless, that's what the last version component is for. If there's unexpected bugs, you fix them, and publish the next patchver within the week. Here's where having a stable branch comes into play. You can't predict or test for every bug, and people can always downgrade.

**Comment by ISSOtm** [comment]
There hasn't been commit activity or error reports for a month, so I'm suggesting we release RGBDS 0.3.9.

Here is the changelog I have written so far:

> rgbasm:
>  - Enforced non-overwritability of some symbols
>  - `-` now allows assembling a file from stdin
>  - Allowed PUSHS to be used before a section declaration
>  - Prevented generating symbols with invalid names using macros
>  - Fixed the precedence of the `==` operator
>  - Added different output formats to bracketed symbols
>  - Fixed a parsing bug with some nested `if` constructs
>  - Improved error reporting now reports actual file line numbers as well as string expansions
>  - Added multiple charmaps (be careful as some feature has been deprecated, a warning has been added about it)
>  - Fixed bug with line numbers in some IF/ELIF/ELSE blocks
>  - Added configurable recursion limit to prevent infinite loops
>  - Fixed unary NOT being a no-op on constant expressions
>  - Made behavior consistent whether outputting a .o file or not
>  - Allowed tabs to be used before line continuations
>  - Allowed sections without content to be placed anywhere
>  - Make error message more explicit with macro argument 0
> 
> rgblink:
>  - Improved many error messages
> 
> rgbgfx:
>  - Added an option to use the GBC's color profile
> 
> other:
>  - Added more tests
>  - Did some internal cleanup
>  - Improved cross-platform compatibility of test suite
> 
> Also fixed a lot more bugs and crashes in rgbasm and rgblink.

Does anyone have any objections? Unless something comes up, I will try to release by the end of the week.
