### ISSUE TITLE
Document exporting EQUates

### ISSUE THREAD

**Issue by pinobatch** [rednex/rgbds#436]
From [`man 5 rgbasm`](https://rednex.github.io/rgbds/rgbasm.5.html):

> EQUates cannot be exported and imported.

It turns out that they can be exported using `GLOBAL` below the constant's definition. I've attached a small example (requiring RGBDS and GNU Make) to demonstrate that `EXPORT` and `GLOBAL` do in fact work with `EQU`: [equate_export_mcve.zip](https://github.com/rednex/rgbds/files/3699189/equate_export_mcve.zip)

I consider this functionality desirable for a couple reasons: an arbitrary distinction between labels and constants makes little sense, and ca65 (the assembler of [cc65](https://github.com/cc65/cc65)) allows exporting its counterpart to EQUates. I use this in asset converters, for example, to write out the width, height, and tile count of graphics that have been converted. (These converters are somewhat more specialized than what RGBGFX does: GBC multicolor maps, sprite sheets with variable offsets, proportional fonts, compression, etc.)

So please remove "EQUates cannot be exported and imported" from the manual.

(A source code comment in the MCVE refers to #421.)

**Comment by ISSOtm** [comment]
It should be mentioned that `EQU` didn't use to work with `EXPORT` until somewhere since 0.3.8; when exactly isn't interesting, imo, as the feature is quite welcome.

**Comment by ISSOtm** [comment]
Fixed by #455.
