### ISSUE TITLE
[Feature request] Allow RGBLINK to determine the target of a `rst`

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#448]
This shouldn't be too problematic: check that the symbol resolves to one of the 8 possible locations, and produce the corresponding opcode.
This would be part of a new object file specification, breaking backwards compatibility, but the new linker has support for reading several versions, so I believe it should be OK.

**Comment by pinobatch** [comment]
The motivation, I assume, is to allow things like `rst wait_vblank_irq`.

For comparison, the macro pack "ca83" for ca65 also allows this. As [its `rst` implementation](https://github.com/pinobatch/little-things-gb/blob/42bcf284aafd63cf036219d55c0b3c311c7132fe/ca83/src/sm83isa.mac#L432) shows, this instruction doesn't even require specific linker support, just support for link-time expressions and assertions (see #292). Once that lands, RGBASM can assert that `(target & $38) == target` and emit `.db target | $C7`.

**Comment by ISSOtm** [comment]
Well, it seems it'd be easier to add a new patch type instead of bolting on a check. Error reporting would also probably suffer.

**Comment by pinobatch** [comment]
Related issue in WLA-DX: https://github.com/vhelin/wla-dx/issues/213
