### ISSUE TITLE
Allow ROMX sections to be used in tiny mode

### ISSUE THREAD

**Issue by nitro2k01** [rednex/rgbds#462]
In current RGBDS, the documentation for tiny mode states:

> Expand the ROM0 section size from 16KiB to the full 32KiB assigned to ROM and prohibit the use of ROMX sections.  Useful for ROMs that fit in 32 KiB.

This is contrary to the original version of RGBDS where the documentation stated:

> Small mode forces all DATA/CODE sections to be of type HOME and increases the HOME section size from 16kB to 32kB. This also means that CODE/DATA/HOME sections are written to the final image in the order you have specified in the linkfile.

Allowing `ROMX` section in tiny mode would allow source files to be shared across projects, or potentially configurations of the same project, without modifying the section declaration or using conditionals/macro trickery.

Desired behavior: In tiny mode, `ROMX` sections would be placed over the full `$0-7FFF` area in the same way as `ROM0` sections currently are. The `BANK` value, if specified, would either be ignored or possibly restricted to using only a value of `1`.

**Comment by pinobatch** [comment]
In particular, aliasing `ROMX` to `ROM0` in tiny mode would make it easier to transition a project between 32K and 64K cartridges.

**Comment by ISSOtm** [comment]
I'm OK with aliasing ROMX sections to ROM0; it might be a good idea to add a warning for this? I would see it added to `-Wextra`.
As for allowing and restricting `BANK[]`, the assembler is unaware of tiny mode, so it'd be implemented in the linker, as bumming as it might be. A possible implementation would be to iterate over all ROMX sections in tiny mode before anything else, and if they are marked as bank 1, turn them into ROM0 sections.

Now here comes a problem: do we want ROMX sections to land in $0000-3FFF? This may break assumptions made about their placement. Do those matter?

**Comment by nitro2k01** [comment]
> Now here comes a problem: do we want ROMX sections to land in $0000-3FFF? This may break assumptions made about their placement. Do those matter?

That would be ok. The whole point is of tiny mode is to remove those assumptions and allow code to be packed tightly across the whole 32k area, including the 16k boundary. A 32k ROM is not supposed to use bank switching anyway. If you want those assumptions to hold, the correct solution is to use the standard mode.

Only allowing sections placed in bank 1 to be aliased was meant to be a conservative implementation, and is not strictly necessary. RGBDS originally did not have that restriction. And to be clear, in either case, ROMX sections without an explicit bank declaration should always be allowed.

One little winkle is, what should `BANK()` return? In my opinion (again, to be conservative) is that maybe it should actually always return 1. Reasoning: If there is code for bank switched calls (which there shouldn't be, but if there is) a value of 1 would give the smallest likelyhood of crashing the code if it runs on a cartridge with a MBC of some kind. Writing 1 to `$2000` will then select the bank that should have been permanently selected anyway.

**Comment by ISSOtm** [comment]
> If you want those assumptions to hold, the correct solution is to use the standard mode.

Fair point. That's how it'll be, then.

Sections explicitly placed in banks other than 1 should produce an error, and everything else should be forced into bank 1. The way the new linker works should make this painless, only needing to change the bank range of the ROMX space [like this](https://github.com/rednex/rgbds/blob/373762dedcbd0f6a4b59c43fbc22884337c7380c/src/link/main.c#L175). ROM0 sections would still have a "bank" of 0.

Minor gain: this should allow ROMX sections without a bank number to be used with overlays when tiny mode is selected, as per #288. :tada:
