### ISSUE TITLE
Passing an out-of-bounds address to a section causes rgbasm to silently fail and then rgblink to segfault

### ISSUE THREAD

**Issue by Syndace** [rednex/rgbds#471]
When defining a section and requesting an address that is out-of-bounds, `rgbasm` finishes instantly without actually assembling the code, but does not show any errors and also creates an object file. When running `rgblink` on that object file, it segfaults. A minimal example is as simple as that:

```asm
SECTION "Oops", HRAM[$0]
    ds 1
```

you don't even have to add a header or anything else.

**Comment by ISSOtm** [comment]
Confirmed to reproduce on current `master` (ish, but relevant code hasn't been touched)
```
issotm@sheik-kitty tmp.A1aMZ3xvmP% cat -n a.asm       
     1	SECTION "Oops", HRAM[0]
     2		ds 1
     3		WARN "O RLY?"
issotm@sheik-kitty tmp.A1aMZ3xvmP% rgbasm -V          
rgbasm v0.3.9-93-gfb22d12-dirty
issotm@sheik-kitty tmp.A1aMZ3xvmP% rgbasm -o o.o a.asm
issotm@sheik-kitty tmp.A1aMZ3xvmP% rgblink -o g.gb o.o
src/link/output.c:83:24: runtime error: member access within null pointer of type 'struct SortedSections'
zsh: segmentation fault (core dumped)  rgblink -o g.gb o.o
```
The part where a .o file is still output might be fixed by #451, but the part where RGBLINK segfaults is a problem nonetheless. RGBASM being significantly more complex, I will first fix RGBLINK.

**Comment by ISSOtm** [comment]
The RGBLINK segfault was fixed in 558e8f46ff578f713147343148c8b46e789c965f by adding more sanity checks. A regression test was added in 2c523649785a4ee9bb21f16148affafcfc3a8a94, too.

**Comment by ISSOtm** [comment]
Actually, RGBASM processes the code just fine?
```
issotm@sheik-kitty tmp.A1aMZ3xvmP% cat -n a.asm
     1	SECTION "Oops", HRAM[0]
     2		ds 1
     3		WARN "O RLY?"
issotm@sheik-kitty tmp.A1aMZ3xvmP% ~/rgbds/rgbasm -Wuser a.asm
warning: a.asm(3): [-Wuser]
    O RLY?
```
If you mean that you expect RGBASM to perform address checking as well, I can agree with that.

**Comment by Syndace** [comment]
Hmm yeah, it seems like rgbasm actually processes the whole code contrary to what I initially reported. I was sure that it ignored all other kinds of errors while the faulty section was present, but I can't reproduce, so I guess everything is fine.

But yes, address range checking on rgbasm would be cool.
