### ISSUE TITLE
Missing license headers

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#474]
I've just noticed that there are a lot of files with no license headers:

https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/hashmap.c

https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/symbol.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/section.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/script.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/patch.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/output.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/object.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/assign.c

https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/asm/warning.c
https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/include/asm/warning.h

Also, do we need this file? https://github.com/rednex/rgbds/blob/50f091ab7ced12e76f458a7a55e961839b5c1e80/src/link/.gitignore

**Comment by ISSOtm** [comment]
Is #475 correct?

**Comment by AntonioND** [comment]
Looks ok to me.

**Comment by ISSOtm** [comment]
Fixed by #475.
