### ISSUE TITLE
Release tarballs should contain only freely licensed files

### ISSUE THREAD

**Issue by bentley** [rednex/rgbds#499]
The tarball uploaded under the releases section contains the entire testsuite. This includes some significant external projects, some nonfree.

As a matter of course, several open source package managers mirror upstream distfiles. I know firsthand that OpenBSD ports, FreeBSD ports, and NetBSD pkgsrc do. This means the fact that the RGBDS distfile contains source code without an explicit license to redistribute is a problem.

ucity (being GPL) has a redistribute clause. Other projects do not, and likely never will. I don’t mind these being part of the test suite, but please *don’t* include them in the release tarball.

**Comment by ISSOtm** [comment]
Right, my bad. This really, really sounds like we should add a `make` target for building at least some release assets...

**Comment by ISSOtm** [comment]
I made a new `make dist` target, and already updated the 0.4.0 tarball. Is that one fine? If yes, I will also update older ones if needed, and commit the Makefile changes.

**Comment by bentley** [comment]
Filename shouldn’t contain ‘v’. Other than that, fine with me.

**Comment by ISSOtm** [comment]
Fixed that. Will proceed with the rest, then.
