### ISSUE TITLE
Binary and manpage permissions?

### ISSUE THREAD

**Issue by JL2210** [rednex/rgbds#501]
The usual permissions for installed binaries and manpages are `755` and `644`, respectively. This allows the owner of the files to modify them (even though this is unnecessary).

However, RGBDS installs these files with permissions `555` and `444`. Why is this?

Is there any particular reason not to have them as `755` and `644`?

**Comment by ISSOtm** [comment]
Short answer: no idea :D
You might want to ask some of the older maintainers (@AntonioND ?), I have just never touched this.

**Comment by AntonioND** [comment]
That's most likely a mistake. You really need that "execute" permission for the binaries...

**Comment by JL2210** [comment]
The binaries have the execute permission, hence "respectively". But none of
the files have the (unnecessary, but standard) write permission bit set for
the owner.

**Comment by AntonioND** [comment]
Oh, right. Sorry, I checked this message while walking and I wasn't paying a lot of attention.

**Comment by JL2210** [comment]
I have a PR ready which changes this. It also changes the use of `/man` to `/share/man` because the latter is also more common. I'll go ahead and open it and see if there are any objections.

**Comment by ISSOtm** [comment]
Fixed by #502.
