### ISSUE TITLE
Jumping to a nonexistent label causes RGBLINK to crash

### ISSUE THREAD

**Issue by JL2210** [rednex/rgbds#512]
Linking this assembly file (`test.asm`) causes a segfault in `rgblink`:

```
SECTION "test",ROM0
entry:
        jr nonexistent_label
```

Command-line:
```
rgbasm test.asm -o test.o
rgblink test.o -o test.gb
```

Output from `make develop` version:
```
src/link/patch.c:340:21: runtime error: member access within null pointer of type 'const struct Symbol'
Segmentation fault
```

This happens with both `jr` and `jp`. Haven't tried anything else.

**Comment by leuat** [comment]
Yeah same problem here. I'm making a wrapper around rgbasm in TRSE (www.turborascal.com), and the assembler doesn't produce any warnings/errors when trying to call / jp to incorrect labels, making debugging *very* hard to do...

**Comment by aaaaaa123456789** [comment]
This kind of thing _definitely_ needs a test.

**Comment by JL2210** [comment]
It's really the linker's fault that it doesn't check for nonexistent
symbols. The assembler doesn't know if the label exists or not until the
program is linked.

**Comment by leuat** [comment]
well - it would be amazing if the linker could provide an helpful error message ("unknown label XXX on line 542") instead of a segfault =) I use the error messages to automatically trace back to the source code

**Comment by ISSOtm** [comment]
Wut? I'm surprised this isn't caught *at all*; this should also cause segfaults no matter which expression you use it in, not just jumps.

**Comment by ISSOtm** [comment]
```
issotm@sheik-kitty ~% rgbds/rgbasm -V
rgbasm v0.4.0-28-g828edb7-dirty
issotm@sheik-kitty ~% echo 'SECTION"test",ROM0\nentry:\njr noexist' | rgbds/rgbasm -o /tmp/o -
issotm@sheik-kitty ~% rgbds/rgblink /tmp/o
src/link/patch.c:340:21: runtime error: member access within null pointer of type 'const struct Symbol'
zsh: segmentation fault (core dumped)  rgbds/rgblink /tmp/o
```
Reproduced on current master, I'm as surprised as you are.

**Comment by ISSOtm** [comment]
It's even more embarrassing to see that an identical case was already handled a couple of lines above...

**Comment by leuat** [comment]
hehe this is fun! I manage my own IDE with a compiler, parser and assembler, and am completely aware of all the bugs that can / will show up in such a project... but this one is pretty severe indeed. Apart from this, I have no more complaints with rgbasm! yet!

**Comment by JL2210** [comment]
@leuat Does your compiler compile C? I'm interested.

**Comment by ISSOtm** [comment]
> am completely aware of all the bugs that can / will show up in such a project...

If you have a good test base, I'm interested in help with #485, if only to have projects to test the WIP new lexer on.

**Comment by leuat** [comment]
see https://www.youtube.com/watch?v=xT-8cyqTbnE or https://www.youtube.com/watch?v=H3FQDnNP2m0  (www.turborascal.com) - it's a cross-platform Pascal compiler for the C64, C128, NES, X86 etc. Lots of tutorials and systems. I decided *today* that it's time to add Z80 support to my compiler, and wanted to use the Gameboy as a test case (similarly to the NES, which I have support for - with image / level / meta sprite resource editing, lots of tutorials etc). So I was kinda surprised when I didn't get any warnings/errors when I tried using incorrect labels etc. 

I'm not entirely sure what #485 entails, but TRSE tends to produce massive .asm files when your program grows large, if that helps =)

**Comment by ISSOtm** [comment]
It's not as much their size as the features they use. Oh well.

**Comment by leuat** [comment]
yeah that is a problem with my compiler: don't really use that much features, since most stuff is filtered through the parser (like: ifdefs and macros etc are all usesless, since it is supposed to be defined in the Pascal source, not the assember). Sorry about that!
