### ISSUE TITLE
Zero-byte SECTIONS print differently in the .map file

### ISSUE THREAD

**Issue by Rangi42** [rednex/rgbds#515]
From pokecrystal:

```
ROM0 bank #0:
  SECTION: $0000-$ffffffff ($0000 bytes) ["NULL"]
           $0000 = NULL
```

I would expect $0000 not $ffffffff, which matches the valid address space and would not break existing parsemap.py and parsemap.c tools.

**Comment by aaaaaa123456789** [comment]
This seems like an evil case of underflow.

**Comment by ISSOtm** [comment]
The problem is that the range boundaries are inclusive, so there is no valid number for the upper bound. (Try a 1-byte section at $0000 and you'll see)
Best I can do is only print the upper boundary, but I'll still break some tools.

**Comment by aaaaaa123456789** [comment]
Perhaps `$FFFF` would be better than `$FFFFFFFF`... although I agree that the only sensible implementation is to show no end point at all.

**Comment by Rangi42** [comment]
No end point sounds like the best option to me too. It would require some tool updates, but actually the changes of `ROM Bank` to `ROM0 bank`/`ROMX bank` and `$0001 bytes` to `$0001 byte` also broke parsemap.py, so may as well break it some more.
