### ISSUE TITLE
Syntax error when macro "ld a, [\1]" is applied to "hl"

### ISSUE THREAD

**Issue by Rangi42** [rednex/rgbds#531]
This is not a major issue, since there's a workaround with if/else/endc below, but it surprised me.

```
SECTION "test", ROM0[0]

Data: db 42


foo: MACRO
	ld a, [\1]
ENDM

	foo Data ; OK
	foo hl ; syntax error


bar: MACRO
if "\1" == "hl"
	ld a, [hl]
else
	ld a, [\1]
endc
ENDM

	bar Data ; OK
	bar hl ; OK
```

**Comment by Rangi42** [comment]
Its occurrence in actual code: https://github.com/pret/pokecrystal/blob/master/macros/code.asm#L13-L28

**Comment by ISSOtm** [comment]
I have no idea how that's even possible, since the string should be interpreted as-is... I wonder what token the lexer is returning.
In any case, this is a lexer problem, so you know what that means... #485

**Comment by aaaaaa123456789** [comment]
I'll take a shot in the dark and assume that `\1` is being substituted after lexing the `[` token, preventing `[hl]` from being read as a unit.

Easy way to test it: does `ld a, [ hl ]` work?

**Comment by Rangi42** [comment]
`ld a, [ \1 ]` does not work either.

**Comment by JL2210** [comment]
> ISSOtm 07/01/2020
> Ah, that'd explain it. We can remove the T_HL_IND token (and related?), and replace it with `'[' T_MODE_HL ']'`
> That should work

**Comment by ISSOtm** [comment]
While we're at this, it may be worth looking into `[$ff00+c]`, which I believe is similarly restrictive.

**Comment by aaaaaa123456789** [comment]
> While we're at this, it may be worth looking into `[$ff00+c]`, which I believe is similarly restrictive.

It is. Support for `[$ff00 + c]` was added as a hack by, as you'd expect, adding that as a token as well.

**Comment by ISSOtm** [comment]
Arguably, correctly handling this is difficult, as `c` is by no means a valid token in an expression. The braces could be removed in favor of `'['` and `']'`, but we'd still need `$ff00\s*+\s*c` to be a single token.

**Comment by aaaaaa123456789** [comment]
Making that a single token is still awkward, because there's no good reason why `c + $ff00` or `65280 + c` shouldn't be allowed. But then again, that's a legacy format for `ldh a, [c]`, so it's not too concerning.

**Comment by ISSOtm** [comment]
It'd be an improvement, at least. Nobody's going to use `65280`, but [hardware.inc defines a `_HW` constant](https://github.com/gbdev/hardware.inc/blob/c755a57d6f47753586760fdd1879011019bdabb8/hardware.inc#L41). That said, *if* it doesn't introduce any grammar conflicts, then maybe that change will be made too.
