### ISSUE TITLE
[Feature request] Zero-padding and octal support in numeric "{symbol}" formatting

### ISSUE THREAD

**Issue by Rangi42** [rednex/rgbds#534]
`"{symbol}"` formatting already supports `d`, `x`, `X`, and `b`. Zero-padding would be nice to have, like `02d` or `08b`.

It's potentially useful for more regular debug `PRINTT` logging, and would also allow neater auto-generated constant names. My current workaround (which has to be repeated both when defining and rept-using all the constants):

```
if n < 10
MOVE_FOR_TM EQUS "TM0{d:n}_MOVE"
else
MOVE_FOR_TM EQUS "TM{d:n}_MOVE"
endc
MOVE_FOR_TM = \1
PURGE MOVE_FOR_TM
```

Also since rgbds supports octal numbers like `&755` (huh! I didn't know that), then a `o` specifier would make sense, if only for completeness.

**Comment by ISSOtm** [comment]
This is starting to make it more generic than it should be, when it was only intended as a sane replacement for previous solutions until #178 is implemented. (Arguably, binary is not really necessary, but let's not worsen the problem then)
