### ISSUE TITLE
Bug: missing decprication warning for labels followed by db

### ISSUE THREAD

**Issue by zelosos** [rednex/rgbds#559]
Labels without a : are deprecated in planed version.
When a label is missing a : a warning is printed.
So:
```
SomeData::
.values      db 0, 1, 2, 3, 4
.otherValues db 5, 6, 7, 8, 9
```
should result in a warning, but it don't.

The same bug could be existing by following commands in the same line.

**Comment by daid** [comment]
Local labels (`.label`) without a semicolon are not deprecated.
