### ISSUE TITLE
rgblink: Consider all objects when determining section order.

### ISSUE THREAD

**Issue by yenatch** [rednex/rgbds#56]
Section names don't carry over between objects. Perhaps this is for the best, but it would be nice to influence section order between several objects.

**Comment by yenatch** [comment]
Apparently it doesn't. Who knew?

**Comment by AntonioND** [comment]
This can be closed now that linkerscripts are implemented. https://github.com/rednex/rgbds/pull/140 They can probably be improved, though, but this should be good enough for most cases, at least for now.
