### ISSUE TITLE
Move the repository under the gbdev organisation

### ISSUE THREAD

**Issue by avivace** [rednex/rgbds#567]
The [gbdev](https://github.com/gbdev) organisation hosts the most popular community driven gbdev projects, including Pan Docs and the awesome gbdev lists. I think RGBDS fits the scope of the org and could enjoy more exposure there.

What do you guys think about rednex/RGBDS -> gbdev/RGBDS? 

No changes to commit premissions and the governance of the repository, obviously.

Any opinion on this, @BenHetherington @bentley ?

**Comment by AntonioND** [comment]
I don't have a strong opinion about this, so whatever you prefer. I think that the whole idea behind the rgbds organisation was to make this a neutral repository, so transfering it to another neutral organisation is probably fine.

**Comment by ISSOtm** [comment]
I agree with this. We'll probably have to change [the history](https://rednex.github.io/rgbds/rgbds.7.html#HISTORY) :P. I've heard some people expressing disapproval of the "rednex" name, so this'd fix that.

This repo would redirect to the new one (as currently does https://github.com/bentley/rgbds since he transferred ownership to here), but I'm not sure the GitHub Pages would redirect... may be a good time to also update the URLs to be shorter. Perhaps host the docs under gbdev.io? (https://gbdev.io/rgbds/rgbasm.5.html instead of https://rednex.github.io/rgbds/rgbasm.5.html, for example)

**Comment by avivace** [comment]
`rgbds.gbdev.io` or `gbdev.io/rgbds` both look good to me!

**Comment by BlitterObjectBob** [comment]
I also dislike the Rednex part of the naming. If the move happens, would RGBDS stay or would that change to something like AGBDS (Assembly GameBoy Development System, or whatever).

**Comment by avivace** [comment]
I think the name should remain RGBDS, regardless of the namespace

**Comment by ISSOtm** [comment]
I'd prefer the sub-domain, I think it looks nicer.

RGBDS would stay, we're **definitely** not changing the same. It's in the executables' names! Plus, I believe the "R" was chosen so the name starts with "RGB", so breaking that would lose some of the name's more amusing connotation. (And "AGB" would be mistaken for the GBA).

**Comment by daid** [comment]
Many projects just drop the "old name" and use the abbrivation as new name. Renaming the project would be confusing, as well as breaks existing Makefiles.

**Comment by ISSOtm** [comment]
cc'ing @bentley for opinion

**Comment by bentley** [comment]
I always liked that the toolchain was named Rednex. But I don’t care if the URL changes.

**Comment by ISSOtm** [comment]
The toolchain's name will not change. @AntonioND, @bentley, @BenHetherington and I shall have rights in a new team under @gbdev. I'll set up a test to see which get redirected of the repo and Pages (since we're using them for the docs), and after that, proceed with the ownership transfer!

**Comment by avivace** [comment]
Great, thank you everyone.
See you on the other side!

j/k
