### ISSUE TITLE
Feature request:  support for more than 4 SRAM banks

### ISSUE THREAD

**Issue by fl4shk** [rednex/rgbds#77]
MBC5 supports more than 4 SRAM banks, which I would like to use in some homebrew I'm developing.  My EMS flash cart in particular has 128 kiB of SRAM.

**Comment by AndreasGB** [comment]
Have a look at my pull request and see if it works for you.

**Comment by AntonioND** [comment]
Fixed here: https://github.com/rednex/rgbds/pull/120
