### ISSUE TITLE
Provide more information on bank overflow errors

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#89]
RGBASM dies when an assembled portion exceeds the maximum size of a bank or section, however the message it outputs is completely uninformative.  Specifically, it does not inform the user as to which line caused the overflow at compile time.  This issue serves as a request to implement this information in the error message for bank/section overflows.

**Comment by PikalaxALT** [comment]
I also propose a slower yet more informative alternative, which is to finish compiling the section, then print the total overrun on exit, assuming the compiler hasn't hit any other exceptions along the way.

**Comment by bentley** [comment]
The bank overflow code really doesn’t make any sense in rgbasm. It can only handle the case of a single section covering an entire bank; it can’t detect multiple banks at all.

It would be nice if rgblink could give more sensible error messages though, like printing out the offending section name. But this will require some work.

**Comment by AntonioND** [comment]
The linker errors were greatly improved with this commit: https://github.com/rednex/rgbds/commit/a75c15ec46180802582a78e13b7c3a6a11721fec

**Comment by AntonioND** [comment]
The current behaviour is inconsistent. If ROM0 or ROMX banks overflow in rgbasm, you get something like `error: Section 'Test' is too big (old size 0 + 16385 > 16384)`. Any other type of section doesn't make it complain, so rgblink complains about it not being able to place it anywhere. There's a `void checkcodesection(SLONG size)` but nothing similar for RAM sections.

Also, the current check is kind of useless as it doesn't inform of the line that caused the error or the total extra size.

It would be really easy to remove this current check and add a proper one right before writing the object file. It could check all sections and, if the size is too big for its type, complain.

However, I don't think it makes sense to do so. ROM0, ROMX, WRAM0 and WRAMX sections can have different sizes depending on the option flags passed to rgblink. It makes sense for rgblink to check this before trying to place any section (and output the size of the section and the max size allowed for that type of section), but I don't think that rgbasm should do anything about it.

**Comment by Ben10do** [comment]
I agree. I don't see much point in duplicating this check, and if there's anywhere to do it, it's in the linker.

**Comment by AntonioND** [comment]
Not to mention the current check is wrong. There's this `#define MAXSECTIONSIZE 0x4000` that prevents the creation of ROM0 sections that are up to 0x8000 bytes as expected.
